annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.4.8
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Python script to update metadata and automatically build collections.
home: https://truecharts.org/charts/stable/kometa
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kometa.webp
keywords:
  - kometa
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: kometa
sources:
  - https://github.com/kometa-team/kometa
  - https://github.com/trueforge-org/containers/tree/main/apps/kometa
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/kometa
type: application
version: 6.10.1

