annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: operators
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.1.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Watches for empty disk to setup with LVM for use with TopoLVM
home: https://truecharts.org/charts/stable/lvm-disk-watcher
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lvm-disk-watcher.webp
keywords:
  - lvm-disk-watcher
  - loadbalancer
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: lvm-disk-watcher
sources:
  - https://github.com/lvm-disk-watcher/lvm-disk-watcher
  - https://github.com/trueforge-org/containers/tree/main/apps/lvm-disk-watcher
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/lvm-disk-watcher
  - https://lvm-disk-watcher.universe.tf
type: application
version: 5.10.0

