annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Network-Messenger
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Creates a simple webpage for Slack invite signups
home: https://truecharts.org/charts/stable/slack-invite
icon: https://truecharts.org/img/hotlink-ok/chart-icons/slack-invite.webp
keywords:
  - slack-invite
  - Network-Messenger
  - Productivity
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: slack-invite
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/slack-invite
  - https://hub.docker.com/r/ninthwalker/slack-invite
  - httpss://github.com/ninthwalker/slack-invite
type: application
version: 9.10.1

