annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.2.54
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Kanboard is a free and open source Kanban project management software.
home: https://truecharts.org/charts/stable/kanboard
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kanboard.webp
keywords:
  - kanboard
  - kanban
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: kanboard
sources:
  - https://ghcr.io/kanboard/kanboard
  - https://github.com/kanboard/kanboard
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/kanboard
type: application
version: 20.10.1

