annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.18.1
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A Python based monitoring and tracking tool for Plex Media Server
home: https://truecharts.org/charts/stable/tautulli
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tautulli.webp
keywords:
  - tautulli
  - plex
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: tautulli
sources:
  - https://ghcr.io/tautulli/tautulli
  - https://github.com/Tautulli/Tautulli
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/tautulli
type: application
version: 22.12.1

