annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Your gateway to the world of crypto
home: https://truecharts.org/charts/stable/crypto-exchanges-gateway
icon: https://truecharts.org/img/hotlink-ok/chart-icons/crypto-exchanges-gateway.webp
keywords:
  - crypto-exchanges-gateway
  - Productivity
  - Crypto
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: crypto-exchanges-gateway
sources:
  - https://github.com/aloysius-pgast/crypto-exchanges-gateway
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/crypto-exchanges-gateway
  - https://hub.docker.com/r/apendergast/crypto-exchanges-gateway
type: application
version: 9.10.1

