annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: machine-learning
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.10.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Whisper is a general-purpose speech recognition model.
home: https://truecharts.org/charts/stable/whisper-asr-webservice
icon: https://truecharts.org/img/hotlink-ok/chart-icons/whisper-asr-webservice.webp
keywords:
  - whisper-asr-webservice
  - machine-learning
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: whisper-asr-webservice
sources:
  - https://github.com/ahmetoner/whisper-asr-webservice
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/whisper-asr-webservice
  - https://hub.docker.com/r/onerahmet/openai-whisper-asr-webservice
type: application
version: 8.12.0

