annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: networking
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.15.1
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.9.1
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Managing Nginx proxy hosts with a simple, powerful interface.
home: https://truecharts.org/charts/stable/nginx-proxy-manager
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nginx-proxy-manager.webp
keywords:
  - nginx-proxy-manager
  - nginx
  - reverse-proxy
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: nginx-proxy-manager
sources:
  - https://github.com/NginxProxyManager/nginx-proxy-manager
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/nginx-proxy-manager
  - https://hub.docker.com/r/jc21/nginx-proxy-manager
  - https://nginxproxymanager.com/
type: application
version: 15.20.0

