annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 6.1.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Redmine is a flexible project management web application written using Ruby on Rails framework.
home: https://truecharts.org/charts/stable/redmine
icon: https://truecharts.org/img/hotlink-ok/chart-icons/redmine.webp
keywords:
  - project
  - management
  - time
  - tracking
  - ticket
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: redmine
sources:
  - https://github.com/redmine/redmine
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/redmine
  - https://hub.docker.com/_/redmine
type: application
version: 16.10.0

