annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.0.19.3011
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Smart PVR for newsgroup and bittorrent users
home: https://truecharts.org/charts/stable/sonarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sonarr.webp
keywords:
  - sonarr
  - torrent
  - usenet
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: sonarr
sources:
  - https://ghcr.io/onedr0p/exportarr
  - https://github.com/Sonarr/Sonarr
  - https://github.com/trueforge-org/containers/tree/main/apps/sonarr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/sonarr
type: application
version: 26.10.0

