annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.1.13
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: The open-source core of Pinry, a tiling image board system for people who want to save, tag, and share images, videos and webpages in an easy to skim through format.
home: https://truecharts.org/charts/stable/pinry
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pinry.webp
keywords:
  - pinry
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pinry
sources:
  - https://github.com/pinry/pinry/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/pinry
  - https://hub.docker.com/r/getpinry/pinry
type: application
version: 13.10.1

