annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2201.1.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Booksonic is a platform for accessing the audibooks you own wherever you are
home: https://truecharts.org/charts/stable/booksonic-air
icon: https://truecharts.org/img/hotlink-ok/chart-icons/booksonic-air.webp
keywords:
  - booksonic
  - audiobook
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: booksonic-air
sources:
  - https://ghcr.io/linuxserver/booksonic-air
  - https://github.com/popeen/Booksonic-Air
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/booksonic-air
type: application
version: 17.10.0

