annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 6.15.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Traccar is an open source GPS tracking system.
home: https://truecharts.org/charts/stable/traccar
icon: https://truecharts.org/img/hotlink-ok/chart-icons/traccar.webp
keywords:
  - traccar
  - gps
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: traccar
sources:
  - https://github.com/traccar/traccar
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/traccar
  - https://hub.docker.com/r/traccar/traccar
type: application
version: 21.13.1

