annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.1.5
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: P2P file synchronization application
home: https://truecharts.org/charts/stable/syncthing
icon: https://truecharts.org/img/hotlink-ok/chart-icons/syncthing.webp
keywords:
  - syncthing
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: syncthing
sources:
  - https://github.com/syncthing/syncthing
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/syncthing
  - https://hub.docker.com/r/syncthing/syncthing
  - https://syncthing.net/
type: application
version: 23.11.1

