# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/syncthing/syncthing
  pullPolicy: IfNotPresent
  tag: 2.1.5@sha256:397aa00b92b48d65540ea3ae3cbf271b87bdccbe07a0b7bd7d2debc3a7b29138
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /rest/noauth/health
            readiness:
              path: /rest/noauth/health
            startup:
              path: /rest/noauth/health
service:
  main:
    ports:
      main:
        port: 8384
        targetPort: 8384
  listeners:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 22000
        targetPort: 22000
  listeners-udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 22000
        targetPort: 22000
        protocol: udp
  discovery:
    enabled: true
    ports:
      discovery:
        enabled: true
        port: 21027
        targetPort: 21027
        protocol: udp
persistence:
  config:
    enabled: true
    mountPath: "/var/syncthing"
