annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: customization
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.22.1
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Custom themes for your favorite apps!
home: https://truecharts.org/charts/stable/theme-park
icon: https://truecharts.org/img/hotlink-ok/chart-icons/theme-park.webp
keywords:
  - theme-park
  - customization
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: theme-park
sources:
  - https://github.com/gilbn/theme.park
  - https://github.com/trueforge-org/containers/tree/main/apps/theme-park
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/theme-park
type: application
version: 14.10.1

