# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/theme-park
  pullPolicy: IfNotPresent
  tag: 1.22.2@sha256:f210aff49d9e0de75bdbe083e83136129738fff7db5f42d32bbabe90b36538fb
service:
  main:
    ports:
      main:
        port: 10244
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
