annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.39.4
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: n8n is an extendable workflow automation tool.
home: https://truecharts.org/charts/stable/n8n
icon: https://truecharts.org/img/hotlink-ok/chart-icons/n8n.webp
keywords:
  - workflows
  - automation
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: n8n
sources:
  - https://docs.n8n.io/
  - https://ghcr.io/n8n-io/n8n
  - https://github.com/n8n-io/n8n
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/n8n
type: application
version: 21.40.3

