# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/freshrss
  pullPolicy: IfNotPresent
  tag: 1.29.1@sha256:7f7f276244da91720e40fee50dd0895b5d59d7888ea75a404ec7495c46fbfbb6
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10010
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
