annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 5.6.0
dependencies:
  - name: common
    version: 29.17.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Wallos - Self Hosted Subscription tracker
home: https://truecharts.org/charts/stable/wallos
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wallos.webp
keywords:
  - dashboard
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: wallos
sources:
  - https://ghcr.io/ellite/wallos
  - https://github.com/ellite/Wallos
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/wallos
type: application
version: 11.7.0

