# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/ellite/wallos
  tag: 5.7.1@sha256:8defb438c52f5c1b2555f86d4abae6a428ff4968f0959ee82b4fa387844ee273
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 80

persistence:
  database:
    enabled: true
    mountPath: "/var/www/html/db"
  logos:
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"
