# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/ellite/wallos
  tag: 5.6.0@sha256:a4d6f6dc9e5abb672e8ae09730427493b4aa3e936e14f97e3d90df55d0e7b3a1
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 80

persistence:
  database:
    enabled: true
    mountPath: "/var/www/html/db"
  logos:
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"
