# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/ellite/wallos
  tag: 5.5.1@sha256:6045bcc9ae548a0a977f2a9efa2a2c2ab552d17ad3d85c7bb9ff4ed9cdaa6f7f
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 80

persistence:
  database:
    enabled: true
    mountPath: "/var/www/html/db"
  logos:
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"
