annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Tools-Utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A tool that can automatically download free seeds and delete them after the free time expires.
home: https://truecharts.org/charts/stable/pt-helper
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pt-helper.webp
keywords:
  - pt-helper
  - Tools-Utilities
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pt-helper
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/pt-helper
  - https://hub.docker.com/r/crazyq/pt_helper
type: application
version: 9.10.1

