annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: test
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.2.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Container for proxmox backup server
home: https://truecharts.org/charts/stable/proxmox-backup-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/proxmox-backup-server.webp
keywords:
  - proxmox-backup-server
  - pbs
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: proxmox-backup-server
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/proxmox-backup-server
  - https://hub.docker.com/r/ayufan/proxmox-backup-server
type: application
version: 8.11.1

