annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.16.5
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: The personal, minimalist, super-fast, database free, bookmarking service.
home: https://truecharts.org/charts/stable/shaarli
icon: https://truecharts.org/img/hotlink-ok/chart-icons/shaarli.webp
keywords:
  - shaarli
  - Productivity
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: shaarli
sources:
  - https://github.com/shaarli/Shaarli
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/shaarli
  - https://hub.docker.com/r/shaarli/shaarli
type: application
version: 9.10.1

