annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: tools
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.8.2
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: ESPHome is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems.
home: https://truecharts.org/charts/stable/esphome
icon: https://truecharts.org/img/hotlink-ok/chart-icons/esphome.webp
keywords:
  - esphome
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: esphome
sources:
  - https://github.com/esphome/esphome
  - https://github.com/trueforge-org/containers/tree/main/apps/esphome
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/esphome
type: application
version: 25.15.0

