annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Device Plugin to expose tun-device on talos
home: https://truecharts.org/charts/stable/generic-device-plugin
icon: https://truecharts.org/img/hotlink-ok/chart-icons/generic-device-plugin.webp
keywords:
  - jackett
  - torrent
  - usenet
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: generic-device-plugin
sources:
  - https://ghcr.io/squat/generic-device-plugin
  - https://github.com/squat/generic-device-plugin
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/generic-device-plugin
type: application
version: 3.10.0

