annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: games
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.8.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Skyrim Together Reborn server files.
home: https://truecharts.org/charts/stable/st-reborn-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/st-reborn-server.webp
keywords:
  - st-reborn-server
  - gameserver
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: st-reborn-server
sources:
  - https://github.com/tiltedphoques/TiltedEvolution
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/st-reborn-server
  - https://hub.docker.com/r/tiltedphoques/st-reborn-server
type: application
version: 9.10.1

