annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 20240301.0.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: JTS3ServerMod by Stefan1200
home: https://truecharts.org/charts/stable/jts3servermod
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jts3servermod.webp
keywords:
  - teamspeak
  - jts3servermod
  - teamspeak-bot
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: jts3servermod
sources:
  - https://ghcr.io/galexrt/jts3servermod
  - https://github.com/galexrt/container-jts3servermod
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/jts3servermod
  - https://www.stefan1200.de/documentation/jts3servermod/readme.html
  - https://www.stefan1200.de/forum/index.php?PHPSESSID=r0m44032akt9jk7903ru9ejv2f&topic=2.0
type: application
version: 5.10.1

