annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.7.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Create live TV channel streams from media on your Plex servers.
home: https://truecharts.org/charts/stable/dizquetv
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dizquetv.webp
keywords:
  - dizqueTV
  - dizquetv
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: dizquetv
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/dizquetv
  - https://github.com/vexorian/dizquetv
  - https://hub.docker.com/r/vexorian/dizquetv
type: application
version: 18.10.1

