annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 26.08.3
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: PuTTY is a free and open-source terminal emulator, serial console and network file transfer application.
home: https://truecharts.org/charts/stable/putty
icon: https://truecharts.org/img/hotlink-ok/chart-icons/putty.webp
keywords:
  - ssh
  - putty
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: putty
sources:
  - https://github.com/jlesage/docker-putty
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/putty
  - https://hub.docker.com/r/jlesage/putty
type: application
version: 15.13.1

