annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: The IYUU automatic seeding tool can automatically seed most PT sites in China, support downloader clusters, multiple disks, multiple download directories, connecting to remote downloaders, etc.
home: https://truecharts.org/charts/stable/iyuuplus
icon: https://truecharts.org/img/hotlink-ok/chart-icons/iyuuplus.webp
keywords:
  - iyuuplus
  - pt
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: iyuuplus
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/iyuuplus
  - https://hub.docker.com/r/iyuucn/iyuuplus
type: application
version: 13.10.1

