annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Cloud
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: 'Homepage: http://bpatrik.github.io/pigallery2/'
home: https://truecharts.org/charts/stable/pigallery2
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pigallery2.webp
keywords:
  - pigallery2
  - Cloud
  - MediaApp-Video
  - MediaApp-Music
  - MediaApp-Photos
  - MediaServer-Video
  - MediaServer-Music
  - MediaServer-Photos
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pigallery2
sources:
  - https://github.com/bpatrik/pigallery2
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/pigallery2
  - https://hub.docker.com/r/bpatrik/pigallery2
type: application
version: 9.10.1

