annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 5.1.6
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: A PHP-based self-hosted URL shortener that can be used to serve shortened URLs under your own custom domain.
home: https://truecharts.org/charts/stable/shlink
icon: https://truecharts.org/img/hotlink-ok/chart-icons/shlink.webp
keywords:
  - url
  - shortener
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: shlink
sources:
  - https://github.com/shlinkio/shlink
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/shlink
  - https://hub.docker.com/r/shlinkio/shlink
type: application
version: 22.20.1

