annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: CadQuery is an intuitive, easy-to-use Python module for building parametric 3D CAD models. Using CadQuery, you can write short, simple scripts that produce high quality CAD models. It is easy to make many different objects using a single script that can be customized.
home: https://truecharts.org/charts/stable/cadquery-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cadquery-server.webp
keywords:
  - cadquery-server
  - Productivity
  - Tools-Utilities
  - Other
  - Network-Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: cadquery-server
sources:
  - https://github.com/roipoussiere/cadquery
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/cadquery-server
  - https://hub.docker.com/r/cadquery/cadquery-server
type: application
version: 9.10.1

