annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Tools-Utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: stable
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Vertex
home: https://truecharts.org/charts/stable/vertex
icon: https://truecharts.org/img/hotlink-ok/chart-icons/vertex.webp
keywords:
  - vertex
  - home-automation
  - Tools-Utilities
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: vertex
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/vertex
  - https://gitlab.lswl.in/lswl/vertex
  - https://hub.docker.com/r/lswl/vertex
type: application
version: 9.10.0

