# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/lswl/vertex
  tag: stable@sha256:bf608d6f2d753e22d899ac0dc7a37a7548e994607b24bc3b1aef6e2633f6c783
persistence:
  config:
    enabled: true
    mountPath: /vertex

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "3000"
