image:
  pullPolicy: IfNotPresent
  repository: docker.io/lswl/vertex
  tag: stable@sha256:9ca1765dc8a3b5573e07ff32ec1f340721fc9e7ce0fd867a1dd8d115b386464a
persistence:
  config:
    enabled: true
    mountPath: /vertex
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "3000"
