annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Photo Stream is a simpler home for your photos. Easy to use, self hosted, no tracking, just photos.
home: https://truecharts.org/charts/stable/photo-stream
icon: https://truecharts.org/img/hotlink-ok/chart-icons/photo-stream.webp
keywords:
  - photo-stream
  - Productivity
  - Tools-Utilities
  - MediaApp-Photos
  - MediaServer-Photos
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: photo-stream
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/photo-stream
  - https://github.com/waschinski/photo-stream
  - https://hub.docker.com/r/waschinski/photo-stream
type: application
version: 9.10.1

