annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: network
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.35.0
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: Blocky is a DNS proxy, DNS enhancer and ad-blocker for the local network written in Go
home: https://truecharts.org/charts/stable/blocky
icon: https://truecharts.org/img/hotlink-ok/chart-icons/blocky.webp
keywords:
  - dns
  - blocky
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: blocky
sources:
  - https://0xerr0r.github.io/blocky/
  - https://ghcr.io/0xerr0r/blocky
  - https://ghcr.io/k8s-gateway/k8s_gateway
  - https://github.com/0xERR0R/blocky
  - https://github.com/Mozart409/blocky-frontend
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/blocky
type: application
version: 22.25.1

