annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: proxy
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.9.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: the front-end of a cluster of minecraft-java containers.
home: https://truecharts.org/charts/stable/minecraft-proxy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/minecraft-proxy.webp
keywords:
  - minecraft-proxy
  - minecraft-bungeecord
  - gameserver
  - minecraft
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: minecraft-proxy
sources:
  - https://ghcr.io/itzg/mc-proxy
  - https://github.com/itzg/docker-mc-proxy
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/minecraft-proxy
type: application
version: 7.11.0

