# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.1-java21@sha256:75372ce4cd916fe6c967c4def2962abd3b1936b778752b43a16d5da6c18127c7
  pullPolicy: Always
j8Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.1-java8@sha256:0ecc33237be4fc7f381993097079750592f408a7f2efdb60294d113c44d2a50f
  pullPolicy: Always
j17Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.1-java17@sha256:f11f82a6a79afa8ed22b87f2df4b6160ac7242ea5bff217ef5c8040f8f6a5671
  pullPolicy: Always
j25Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.1-java25@sha256:d52885bf1e5f1ebb88bd19114dbaaf472cdd4ff3dc4f9161fd2018d6ccfd4afd
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 25565
        targetPort: 25577
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25578
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          tty: true
          stdin: true
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            RCON_PASSWORD: "secretrconpass"
            TYPE: "BUNGEECORD"
            ONLINE_MODE: false
            MEMORY: 512M
            INIT_MEMORY: 512M
            MAX_MEMORY: 512M
            NETWORKADDRESS_CACHE_TTL: 60
            REPLACE_ENV_VARIABLES: false
            ENV_VARIABLE_PREFIX: "CFG_"
            # GENERIC_PACKS: "configs-v9.0.1,mods-v4.3.6"
            # GENERIC_PACKS_PREFIX: "https://cdn.example.org/"
            # GENERIC_PACKS_SUFFIX="".zip"
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # PLUGINS: ""
persistence:
  config:
    enabled: true
    mountPath: "/config"
  server:
    enabled: true
    mountPath: "/server"
  plugins:
    enabled: true
    mountPath: "/plugins"
