annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: ssh
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: SSHwifty is a SSH and Telnet connector made for the Web.
home: https://truecharts.org/charts/stable/sshwifty
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sshwifty.webp
keywords:
  - ssh
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: sshwifty
sources:
  - https://github.com/niruix/sshwifty
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/sshwifty
  - https://hub.docker.com/r/niruix/sshwifty
type: application
version: 9.10.1

