annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: AI
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.6.5
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A standalone, self-hosted, fast, free and Open Source Artificial Intelligence microserver for any platform, any language.
home: https://truecharts.org/charts/stable/codeproject-ai-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/codeproject-ai-server.webp
keywords:
  - ai-server
  - sense-ai
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: codeproject-ai-server
sources:
  - https://github.com/codeproject/CodeProject.AI-Server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/codeproject-ai-server
  - https://hub.docker.com/r/codeproject/ai-server
type: application
version: 6.10.1

