image:
  repository: ghcr.io/linuxserver/babybuddy
  pullPolicy: IfNotPresent
  tag: 2.7.1@sha256:03b13fd1a6553c1ce2df97a7c1542ef6c97fc3c3e81db8fc0ff76f40dbb0db49
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10069
        protocol: http
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_ENGINE: "django.db.backends.postgresql"
            DB_NAME: "{{ .Values.cnpg.main.database }}"
            DB_USER: "{{ .Values.cnpg.main.user }}"
            DB_PORT: "5432"
            CSRF_TRUSTED_ORIGINS: ""
            DB_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
persistence:
  config:
    enabled: true
    mountPath: /config
cnpg:
  main:
    enabled: true
    user: babybuddy
    database: babybuddy
