# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/modem7/docker-rickroll
  pullPolicy: IfNotPresent
  tag: latest@sha256:fa1ddd2146959d003165792be76ae8196e972b805e55755c8052163102912eba
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10289
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            TITLE: "Rickroll"
            HEIGHT: "100vh"
            WIDTH: "100%"
            HEADLINE: ""
