annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.4.1
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Index and stream music using apache-musicindex and m3u playlists
home: https://truecharts.org/charts/stable/apache-musicindex
icon: https://truecharts.org/img/hotlink-ok/chart-icons/apache-musicindex.webp
keywords:
  - apache-musicindex
  - streaming
  - m3u
  - playlist
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: apache-musicindex
sources:
  - https://ghcr.io/k8s-at-home/apache-musicindex
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/apache-musicindex
type: application
version: 15.10.1

