annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.24.2558
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: API Support for your favorite torrent trackers.
home: https://truecharts.org/charts/stable/jackett
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jackett.webp
keywords:
  - jackett
  - torrent
  - usenet
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: jackett
sources:
  - https://github.com/Jackett/Jackett
  - https://github.com/geek-cookbook/containers/pkgs/container/jackett
  - https://github.com/trueforge-org/containers/tree/main/apps/jackett
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/jackett
type: application
version: 27.10.4

