# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/jackett
  pullPolicy: IfNotPresent
  tag: 0.24.2544@sha256:7d2429e3407ee2b8e375216d1b2c7ef3329e4a55546aed4e5bd219d6165bf9c6
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
