annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: management
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.9.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Web-based LDAP browser to manage your LDAP server
home: https://truecharts.org/charts/stable/phpldapadmin
icon: https://truecharts.org/img/hotlink-ok/chart-icons/phpldapadmin.webp
keywords:
  - phpldapadmin
  - openldap
  - userrights
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: phpldapadmin
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/phpldapadmin
  - https://gitlab.v2.rancher.geohub.space/g3s/i3s/i3s-helm-catalog
  - https://hub.docker.com/r/osixia/phpldapadmin
type: application
version: 17.10.1

