annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.5.13
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: AppDaemon is a loosely coupled, multi-threaded, sandboxed python execution environment for writing automation apps.
home: https://truecharts.org/charts/stable/appdaemon
icon: https://truecharts.org/img/hotlink-ok/chart-icons/appdaemon.webp
keywords:
  - appdaemon
  - home-automation
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: appdaemon
sources:
  - https://github.com/AppDaemon/appdaemon
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/appdaemon
  - https://hub.docker.com/r/acockburn/appdaemon
type: application
version: 20.10.1

