annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: metrics
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.0.1
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Prometheus Exporter for the official uptimerobot CLI
home: https://truecharts.org/charts/stable/uptimerobot-prometheus
icon: https://truecharts.org/img/hotlink-ok/chart-icons/uptimerobot-prometheus.webp
keywords:
  - uptimerobot
  - prometheus
  - grafana
  - metrics
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: uptimerobot-prometheus
sources:
  - https://github.com/k8s-at-home/charts/tree/master/charts/uptimerobot-prometheus
  - https://github.com/lekpamartin/uptimerobot_exporter
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/uptimerobot-prometheus
  - https://hub.docker.com/r/billimek/prometheus-uptimerobot-exporter
type: application
version: 15.10.0

