annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: MediaServer-Video
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: TwonkyMedia server (TMS) is DLNA-compliant UPnP AV server software from PacketVideo. TwonkyMedia server can be used to share and stream media to most UPnP AV or DLNA-compliant clients, in addition to non-UPnP devices through the HTML, RSS, and JSON supported front ends.
home: https://truecharts.org/charts/stable/twonky-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/twonky-server.webp
keywords:
  - twonky-server
  - MediaServer-Video
  - MediaServer-Music
  - MediaServer-Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: twonky-server
sources:
  - https://github.com/H2CK/twonkyserver
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/twonky-server
  - https://hub.docker.com/r/dtjs48jkt/twonkyserver
type: application
version: 9.10.1

