annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: home-automation
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.9.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A automatic user invitation system for Plex.
home: https://truecharts.org/charts/stable/wizarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wizarr.webp
keywords:
  - wizarr
  - home-automation
  - Tools-Utilities
  - Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: wizarr
sources:
  - https://ghcr.io/wizarrrr/wizarr
  - https://github.com/Wizarrrr/wizarr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/wizarr
type: application
version: 13.14.0

