annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.0.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: pretend-youre-xyzzy, a cards against humanity clone
home: https://truecharts.org/charts/stable/pretend-youre-xyzzy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pretend-youre-xyzzy.webp
keywords:
  - pretend-youre-xyzzy
  - cards
  - against
  - humanity
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pretend-youre-xyzzy
sources:
  - https://github.com/ajanata/PretendYoureXyzzy
  - https://github.com/emcniece/DockerYourXyzzy
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/pretend-youre-xyzzy
  - https://hub.docker.com/r/emcniece/dockeryourxyzzy
type: application
version: 17.10.0

