annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: torrent
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.2.9
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: rTorrent and ruTorrent chart.
home: https://truecharts.org/charts/stable/rtorrent-rutorrent
icon: https://truecharts.org/img/hotlink-ok/chart-icons/rtorrent-rutorrent.webp
keywords:
  - rutorrent
  - torrent
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: rtorrent-rutorrent
sources:
  - https://ghcr.io/crazy-max/rtorrent-rutorrent
  - https://ghcr.io/thde/rtorrent_exporter
  - https://github.com/crazy-max/docker-rtorrent-rutorrent
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/rtorrent-rutorrent
  - https://trueforge.org/truecharts/stable/rtorrent-rutorrent
type: application
version: 8.10.1

