annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.6.26
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Calibre-Web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database.
home: https://truecharts.org/charts/stable/calibre-web
icon: https://truecharts.org/img/hotlink-ok/chart-icons/calibre-web.webp
keywords:
  - calibre-web
  - calibre
  - ebook
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: calibre-web
sources:
  - https://github.com/janeczku/calibre-web
  - https://github.com/trueforge-org/containers/tree/main/apps/calibre-web
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/calibre-web
type: application
version: 22.10.1

