annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: cloud
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.21.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A timed task management panel that supports typescript, javaScript, python3, and shell
home: https://truecharts.org/charts/stable/qinglong
icon: https://truecharts.org/img/hotlink-ok/chart-icons/qinglong.webp
keywords:
  - qinglong
  - task
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: qinglong
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/qinglong
  - https://hub.docker.com/r/whyour/qinglong
type: application
version: 13.11.1

