image:
  repository: docker.io/whyour/qinglong
  pullPolicy: IfNotPresent
  tag: 2.18.1@sha256:065a3c500769e6abd51063a035d74374ec1da1748b184876a20f40ca78d07296
service:
  main:
    ports:
      main:
        targetPort: 5700
        port: 10176
persistence:
  data:
    enabled: true
    mountPath: "/ql/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
