# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/privoce/vocechat-server
  pullPolicy: IfNotPresent
  tag: v0.5.35@sha256:00e910abea4cebb7c73115f7ec6e1e2a0fd812c1a8ac4dda0488b033f07c2a0f

service:
  main:
    ports:
      main:
        protocol: http
        port: 3009

vocechat:
  frontend_url: localhost:3009

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --network.bind
            - 0.0.0.0:{{ .Values.service.main.ports.main.port }}
            - --network.frontend_url
            - "{{ .Values.vocechat.frontend_url }}"

persistence:
  data:
    enabled: true
    mountPath: "/home/vocechat-server/data"
