annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.7.3
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: true
description: Jellyseerr is a fork of Overseerr with support for Jellyfin and Emby. It can be used to manage requests for your media library.
home: https://truecharts.org/charts/stable/jellyseerr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jellyseerr.webp
keywords:
  - jellyseerr
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: jellyseerr
sources:
  - https://github.com/Fallenbagel/jellyseerr
  - https://github.com/trueforge-org/containers/tree/main/apps/jellyseerr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/jellyseerr
type: application
version: 15.6.1

