annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.7.2
dependencies:
  - name: common
    version: 29.17.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Allows you to sync any Joplin client.
home: https://truecharts.org/charts/stable/joplin-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/joplin-server.webp
keywords:
  - joplin
  - notes
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: joplin-server
sources:
  - https://github.com/laurent22/joplin
  - https://github.com/laurent22/joplin/tree/dev/packages/server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/joplin-server
  - https://hub.docker.com/r/joplin/server
type: application
version: 22.11.1

