annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 251130.0.0
dependencies:
  - name: common
    version: 29.17.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.9.1
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: PhotoPrism® is a server-based application for browsing, organizing and sharing your personal photo collection
home: https://truecharts.org/charts/stable/photoprism
icon: https://truecharts.org/img/hotlink-ok/chart-icons/photoprism.webp
keywords:
  - photos
  - photoprism
  - pictures
  - sharing
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: photoprism
sources:
  - https://github.com/photoprism/photoprism
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/photoprism
  - https://hub.docker.com/r/photoprism/photoprism
type: application
version: 30.18.1

