annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: GameServers
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: palworld
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A custom SteamCMD chart that runs Palworld.
home: https://truecharts.org/charts/stable/palworld
icon: https://truecharts.org/img/hotlink-ok/chart-icons/palworld.webp
keywords:
  - palworld
  - GameServers
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: palworld
sources:
  - https://ghcr.io/ich777/steamcmd
  - https://github.com/ich777/docker-steamcmd-server/tree/palworld
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/palworld
type: application
version: 7.10.1

