annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: files
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.13.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Pingvin Share is self-hosted file sharing platform and an alternative for WeTransfer.
home: https://truecharts.org/charts/stable/pingvin-share
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pingvin-share.webp
keywords:
  - file-sharting
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pingvin-share
sources:
  - https://github.com/stonith404/pingvin-share
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/pingvin-share
  - https://hub.docker.com/r/stonith404/pingvin-share
type: application
version: 5.10.0

