annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 9.2.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Lyrion Music Server is a platform for home/office audio streaming.
home: https://truecharts.org/charts/stable/lyrion-music-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lyrion-music-server.webp
keywords:
  - lyrion-music-server
  - logitech-media-server
  - squeezebox
  - audio
  - streaming
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: lyrion-music-server
sources:
  - https://github.com/LMS-Community/slimserver
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/lyrion-music-server
  - https://hub.docker.com/r/lmscommunity/lyrionmusicserver
type: application
version: 6.10.2

