annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: metrics
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.10.0
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A Prometheus exporter for Proxmox Virtual Environment metrics.
home: https://truecharts.org/charts/stable/prometheus-pve-exporter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/prometheus-pve-exporter.webp
keywords:
  - prometheus
  - prometheus-pve-exporter
  - monitoring
  - proxmox
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: prometheus-pve-exporter
sources:
  - https://github.com/prometheus-pve/prometheus-pve-exporter
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/prometheus-pve-exporter
  - https://grafana.com/grafana/dashboards/10347-proxmox-via-prometheus/
  - https://hub.docker.com/r/prompve/prometheus-pve-exporter
type: application
version: 3.12.1

