annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.0.26
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A Fast, Simple, and Flexible, file-based Web-platform.
home: https://truecharts.org/charts/stable/grav
icon: https://truecharts.org/img/hotlink-ok/chart-icons/grav.webp
keywords:
  - grav
  - web
  - platform
  - file
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: grav
sources:
  - https://ghcr.io/linuxserver/grav
  - https://github.com/getgrav/grav/
  - https://github.com/linuxserver/docker-grav
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/grav
type: application
version: 16.6.3

