# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: 2.0.25@sha256:7105cb594dff079cc4d3ab2e06ea238098d11f376d794b058129414b67dee230
service:
  main:
    ports:
      main:
        port: 10012
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
