# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: 2.1.2@sha256:f12b1c46e42101dee7b6727084c567ba0c6edd4d1bfcbe12f61502260e055769
service:
  main:
    ports:
      main:
        port: 10012
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
