annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.53.10
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Want a Movie or TV Show on Plex or Emby? Use Ombi!
home: https://truecharts.org/charts/stable/ombi
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ombi.webp
keywords:
  - ombi
  - plex
  - emby
  - sonarr
  - radarr
  - couchpotato
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: ombi
sources:
  - https://ghcr.io/linuxserver/ombi
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/ombi
type: application
version: 23.10.0

