annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.4.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Photoview is a simple and user-friendly photo gallery.
home: https://truecharts.org/charts/stable/photoview
icon: https://truecharts.org/img/hotlink-ok/chart-icons/photoview.webp
keywords:
  - photo
  - gallery
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: photoview
sources:
  - https://github.com/photoview/photoview
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/photoview
  - https://hub.docker.com/r/viktorstrate/photoview
type: application
version: 17.10.1

