annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Cloud
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.4.1
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A fast and minimal paste bin, written in Python using Quart.
home: https://truecharts.org/charts/stable/hasty-paste
icon: https://truecharts.org/img/hotlink-ok/chart-icons/hasty-paste.webp
keywords:
  - hasty-paste
  - Cloud
  - Productivity
  - Tools-Utilities
  - Network-Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: hasty-paste
sources:
  - https://ghcr.io/enchant97/hasty-paste
  - https://github.com/enchant97/hasty-paste
  - https://github.com/enchant97/hasty-paste/blob/main/docs/install.md
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/hasty-paste
type: application
version: 11.11.0

