annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: GameServers
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Chart file for the new Core Keeper dedicated server running from SteamCMD. (No account etc needed)
home: https://truecharts.org/charts/stable/core-keeper-dedicated-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/core-keeper-dedicated-server.webp
keywords:
  - core-keeper-dedicated-server
  - GameServers
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: core-keeper-dedicated-server
sources:
  - https://github.com/escapingnetwork/core-keeper-dedicated/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/core-keeper-dedicated-server
  - https://hub.docker.com/r/escaping/core-keeper-dedicated
type: application
version: 9.10.1

