annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: home-automation
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.9.2
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Open source home automation that puts local control and privacy first.
home: https://truecharts.org/charts/stable/home-assistant
icon: https://truecharts.org/img/hotlink-ok/chart-icons/home-assistant.webp
keywords:
  - home-assistant
  - home-automation
  - hass
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: home-assistant
sources:
  - https://github.com/cdr/code-server
  - https://github.com/home-assistant/home-assistant
  - https://github.com/trueforge-org/containers/tree/main/apps/go-yq
  - https://github.com/trueforge-org/containers/tree/main/apps/home-assistant
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/home-assistant
type: application
version: 31.4.1

