annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.08.28
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Web GUI for youtube-dl.
home: https://truecharts.org/charts/stable/metube
icon: https://truecharts.org/img/hotlink-ok/chart-icons/metube.webp
keywords:
  - metube
  - media
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: metube
sources:
  - https://ghcr.io/alexta69/metube
  - https://github.com/alexta69/metube
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/metube
type: application
version: 18.15.1

