annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Mailpile is software, an e-mail client. It runs on your desktop or laptop computer and you interact with it by using your web browser. The goal of Mailpile is to allow people to send e-mail in a more secure and private manner than before.
home: https://truecharts.org/charts/stable/mailpile
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mailpile.webp
keywords:
  - mailpile
  - Productivity
  - Network-Web
  - Network-Messenger
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: mailpile
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/mailpile
  - https://hub.docker.com/r/rroemhild/mailpile
  - https://www.mailpile.is/
type: application
version: 9.10.0

