#!/usr/bin/python3
import json
import sys


def migrate(values):
    values.update({
        'appVolumeMounts': {
            'export': {
                'hostPathEnabled': values['minioHostPathEnabled'],
                **({'hostPath': values['minioHostPath']} if values.get('minioHostPath') else {})
            },
        },
    })
    return values


if __name__ == '__main__':
    if len(sys.argv) != 2:
        exit(1)

    print(json.dumps(migrate(json.loads(sys.argv[1]))))
