annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.19.12
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Semaphore is a modern, open source alternative to Ansible Tower. It is a self-hosted web-based solution that allows you to create and manage Ansible projects, playbooks, and roles, while also providing a web interface for running and monitoring Ansible tasks.
home: https://truecharts.org/charts/stable/semaphore
icon: https://truecharts.org/img/hotlink-ok/chart-icons/semaphore.webp
keywords:
  - ansible
  - semaphore
  - cicd
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: semaphore
sources:
  - https://github.com/ansible-semaphore/semaphore
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/semaphore
  - https://hub.docker.com/r/semaphoreui/semaphore
type: application
version: 7.12.0

