annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: home-automation
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.5.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: The Wyoming integration of piper
home: https://truecharts.org/charts/stable/wyoming-piper
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wyoming-piper.webp
keywords:
  - wyoming-piper
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: wyoming-piper
sources:
  - https://github.com/home-assistant/addons/tree/master/piper
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/wyoming-piper
  - https://hub.docker.com/r/rhasspy/wyoming-piper
type: application
version: 9.13.0

