# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/rhasspy/wyoming-piper
  pullPolicy: IfNotPresent
  tag: 2.5.1@sha256:a61b12575e5a05b307983c3172bdf03ef7dd68a6f6093f3b6105a0c65004d0a3

service:
  main:
    ports:
      main:
        port: 10200
        protocol: tcp
        targetPort: 10200

wyoming_piper:
  voice: en_US-lessac-medium
  # custom_voice: ""
  speaker: 0
  length_scale: "1.0"
  noise_scale: "0.667"
  noise_w: "0.333"

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              port: 10200
              type: tcp
            readiness:
              port: 10200
              type: tcp
            startup:
              port: 10200
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /data
