annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.1.5
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A self hosted virtual browser that runs in Chart
home: https://truecharts.org/charts/stable/neko
icon: https://truecharts.org/img/hotlink-ok/chart-icons/neko.webp
keywords:
  - neko
  - video
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: neko
sources:
  - https://ghcr.io/m1k1o/neko/brave
  - https://ghcr.io/m1k1o/neko/chromium
  - https://ghcr.io/m1k1o/neko/firefox
  - https://ghcr.io/m1k1o/neko/google-chrome
  - https://ghcr.io/m1k1o/neko/microsoft-edge
  - https://ghcr.io/m1k1o/neko/remmina
  - https://ghcr.io/m1k1o/neko/tor-browser
  - https://ghcr.io/m1k1o/neko/vivaldi
  - https://ghcr.io/m1k1o/neko/vlc
  - https://ghcr.io/m1k1o/neko/xfce
  - https://github.com/m1k1o/neko
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/neko
type: application
version: 11.20.1

