# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/ronnieroller/media-roller
  tag: latest@sha256:fe2858ab1e9b1121c3fe35ca0c9cd0672b808b150f421cdeb272ce5cd032fcd7
persistence:
  download:
    enabled: true
    mountPath: /download

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
