annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Backup
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.0.826
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: iCloudPD, syncs photos from iDevices to a single directory on TrueNAS.
home: https://truecharts.org/charts/stable/icloudpd
icon: https://truecharts.org/img/hotlink-ok/chart-icons/icloudpd.webp
keywords:
  - icloudpd
  - Backup
  - Cloud
  - Downloaders
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: icloudpd
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/icloudpd
  - https://hub.docker.com/r/boredazfcuk/icloudpd
type: application
version: 10.10.1

