annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: network
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.10.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Light container updating DNS A and/or AAAA records periodically for multiple DNS providers
home: https://truecharts.org/charts/stable/ddns-updater
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ddns-updater.webp
keywords:
  - ddns-updater
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: ddns-updater
sources:
  - https://github.com/qdm12/ddns-updater
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/ddns-updater
  - https://hub.docker.com/r/qmcgaw/ddns-updater
type: application
version: 13.11.1

