annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.7.4
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Stateless cluster local OCI registry mirror.
home: https://truecharts.org/charts/stable/spegel
icon: https://truecharts.org/img/hotlink-ok/chart-icons/spegel.webp
keywords:
  - spegel
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: spegel
sources:
  - https://ghcr.io/spegel-org/spegel
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/spegel
type: application
version: 5.11.1

