# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/homarr-labs/homarr
  tag: v1.77.1@sha256:1f5b892aeef4ad0a4907f075777bbd0ce7120f4cdc53b9f3f028519250421aed
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SECRET_ENCRYPTION_KEY: "changemeplease"
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  appdata:
    enabled: true
    mountPath: "/appdata"
  varrun:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
