# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/songkong/songkong
  tag: latest@sha256:888e3d26cd7cf77428b6cba9f46876abafce8096f7b58b0484e69d134c0b0ed0
persistence:
  music:
    enabled: true
    mountPath: /music
  songkongconfig:
    enabled: true
    mountPath: /songkong

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4567
        protocol: tcp
        targetPort: 4567
