annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: tools
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 11.23.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Full featured Z-Wave Control Panel and MQTT Gateway, using NodeJS and Vue.
home: https://truecharts.org/charts/stable/zwavejs2mqtt
icon: https://truecharts.org/img/hotlink-ok/chart-icons/zwavejs2mqtt.webp
keywords:
  - zwavejs2mqtt
  - zwave-js-ui
  - zwave-js
  - z-wave
  - zwave
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: zwavejs2mqtt
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/zwavejs2mqtt
  - https://github.com/zwave-js/zwave-js-ui
  - https://hub.docker.com/r/zwavejs/zwave-js-ui
type: application
version: 25.19.0

