annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: GameServers
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Runs Ark Survival Evolved and Ark-Server-Manager
home: https://truecharts.org/charts/stable/arksurvivalevolved
icon: https://truecharts.org/img/hotlink-ok/chart-icons/arksurvivalevolved.webp
keywords:
  - arksurvivalevolved
  - arkse
  - GameServers
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: arksurvivalevolved
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/arksurvivalevolved
  - https://hub.docker.com/r/drpsychick/arkserver
type: application
version: 12.10.1

