annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.5.4
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Spotweb is a decentralized usenet community based on the Spotnet protocol.
home: https://truecharts.org/charts/stable/spotweb
icon: https://truecharts.org/img/hotlink-ok/chart-icons/spotweb.webp
keywords:
  - usenet
  - spotweb
  - spotnet
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: spotweb
sources:
  - https://github.com/joachimbaten/spotweb-docker
  - https://github.com/spotweb/spotweb
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/spotweb
  - https://hub.docker.com/r/jbaten/spotweb
type: application
version: 16.10.0

