annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.27.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Looks and smells like Overseerr, does the opposite. Maintenance tool for the Plex ecosystem.
home: https://truecharts.org/charts/stable/maintainerr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/maintainerr.webp
keywords:
  - maintainerr
  - media
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: maintainerr
sources:
  - https://github.com/Maintainerr/Maintainerr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/maintainerr
  - https://hub.docker.com/r/maintainerr/maintainerr
type: application
version: 7.34.0

