annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: file-storage
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 13.0.25
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.9.1
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.9.2
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: Reliable and Performant File Sync and Share Solution
home: https://truecharts.org/charts/stable/seafile
icon: https://truecharts.org/img/hotlink-ok/chart-icons/seafile.webp
keywords:
  - seafile
  - files
  - cloud
  - file-storage
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: seafile
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/seafile
  - https://hub.docker.com/r/seafileltd/seafile-mc
  - https://seafile.com
type: application
version: 15.20.0

