annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: database
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Open source, advanced key-value store.
home: https://truecharts.org/charts/stable/redis
icon: https://truecharts.org/img/hotlink-ok/chart-icons/redis.webp
keywords:
  - redis
  - keyvalue
  - database
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: redis
sources:
  - https://github.com/bitnami/bitnami-docker-redis
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/redis
  - https://hub.docker.com/r/bitnamisecure/redis
type: application
version: 18.10.1

