image:
  pullPolicy: IfNotPresent
  repository: docker.io/mikenye/tar1090
  tag: latest@sha256:663c127fc7f32cd7a26956a206a209613e2caae0fef0c4c72aed00ff4a686726
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8078
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BEASTHOST: <BEASTHOST>
            LAT: xx.xxxxx
            LONG: xx.xxxxx
            MLATHOST: <MLATHOST>
