#!/usr/bin/python3
import json
import re
import sys

from catalog_update.upgrade_strategy import semantic_versioning


RE_STABLE_VERSION = re.compile(r'\d+.\d+.\d+.\d+')


def newer_mapping(image_tags):
    key = list(image_tags.keys())[0]
    version = semantic_versioning(sorted(
        [tag for tag in image_tags[key] if RE_STABLE_VERSION.fullmatch(tag) and tag.split('.')[2] != '0'],
        reverse=True
    ))
    if not version:
        return {}

    return {
        'tags': {key: version},
        'app_version': version,
    }


if __name__ == '__main__':
    try:
        versions_json = json.loads(sys.stdin.read())
    except ValueError:
        raise ValueError('Invalid json specified')

    print(json.dumps(newer_mapping(versions_json)))
