annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: database
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 26.8.2.7
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: ClickHouse is a column-oriented database management system (DBMS) for online analytical processing of queries (OLAP).
home: https://truecharts.org/charts/stable/clickhouse
icon: https://truecharts.org/img/hotlink-ok/chart-icons/clickhouse.webp
keywords:
  - database
  - clickhouse
  - sql
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: clickhouse
sources:
  - https://clickhouse.com/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/clickhouse
  - https://hub.docker.com/r/clickhouse/clickhouse-server
type: application
version: 18.16.1

