annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.16.4
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.9.2
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: Weblate is a copylefted libre software web-based continuous localization system
home: https://truecharts.org/charts/stable/weblate
icon: https://truecharts.org/img/hotlink-ok/chart-icons/weblate.webp
keywords:
  - translate
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: weblate
sources:
  - https://docs.weblate.org/en/latest/
  - https://github.com/WeblateOrg/docker
  - https://github.com/WeblateOrg/docker-compose
  - https://github.com/WeblateOrg/weblate
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/weblate
  - https://hub.docker.com/r/weblate/weblate
type: application
version: 20.18.0

