# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/oscam
  pullPolicy: IfNotPresent
  tag: 11966-ls23@sha256:fd183a3f65ac817685a5e35bad1028155b05fe4b26d5f8cd2bdccfd84d95e6b6
service:
  main:
    ports:
      main:
        port: 10062
        targetPort: 8888
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 20
