annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2021.11.21
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Endlessh is an SSH tarpit that very slowly sends an endless, random SSH banner.
home: https://truecharts.org/charts/stable/endlessh
icon: https://truecharts.org/img/hotlink-ok/chart-icons/endlessh.webp
keywords:
  - endlessh
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: endlessh
sources:
  - https://ghcr.io/linuxserver/endlessh
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/endlessh
type: application
version: 13.10.1

