annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 16.4.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A photo gallery software for the web.
home: https://truecharts.org/charts/stable/piwigo
icon: https://truecharts.org/img/hotlink-ok/chart-icons/piwigo.webp
keywords:
  - piwigo
  - gallery
  - photo
  - image
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: piwigo
sources:
  - https://ghcr.io/linuxserver/piwigo
  - https://github.com/linuxserver/docker-piwigo
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/piwigo
type: application
version: 20.21.1

