# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/nodered/node-red
  pullPolicy: IfNotPresent
  tag: 5.0.7@sha256:a649dd711d55490151a2c39a8e48ad0c44325488fbc0e66315f2d2e19e5e1ace
service:
  main:
    ports:
      main:
        port: 1880
        targetPort: 1880
persistence:
  data:
    enabled: true
    mountPath: "/data"

workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
