# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/wiserain/flexget
  pullPolicy: IfNotPresent
  tag: 3.20.13@sha256:54ad3e63df8548d61d9444ef72a6ab2d292b858a22283bfa029d39ae54d464af
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            FG_LOG_LEVEL: info
            FG_LOG_FILE: flexget.log
            FG_WEBUI_PASSWD: "jLeT78KBDPW"
service:
  main:
    ports:
      main:
        port: 10174
        targetPort: 5050
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
