annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: downloads
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 26.08.2
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: JDownloader is a free, open-source download management tool with a huge community of developers that makes downloading as easy and fast as it should be.
home: https://truecharts.org/charts/stable/jdownloader2
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jdownloader2.webp
keywords:
  - jdownloader
  - download
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: jdownloader2
sources:
  - https://github.com/jlesage/docker-jdownloader-2
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/jdownloader2
  - https://hub.docker.com/r/jlesage/jdownloader-2
  - https://jdownloader.org/
type: application
version: 22.12.1

