annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: main
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A web-based tool for processing images and converting documents with a simple interface.
home: https://truecharts.org/charts/stable/reubah
icon: https://truecharts.org/img/hotlink-ok/chart-icons/reubah.webp
keywords:
  - reubah
  - image-processor
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: reubah
sources:
  - https://ghcr.io/dendianugerah/reubah
  - https://github.com/dendianugerah/reubah
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/reubah
type: application
version: 3.10.0

