# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/rhasspy/wyoming-whisper
  pullPolicy: IfNotPresent
  tag: 3.8.0@sha256:c3c6a1bca0b72ad8df0fbb00d315ff58f349270d3c40b9611b8a7f6ae28fd58f

service:
  main:
    ports:
      main:
        port: 10300
        protocol: tcp
        targetPort: 10300

wyoming_whisper:
  language: en
  model: tiny-int8
  #  custom_model: ""
  beam_size: 1
  initial_prompt: ""

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              port: 10300
              type: tcp
            readiness:
              port: 10300
              type: tcp
            startup:
              port: 10300
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /data
  cache:
    enabled: true
    mountPath: /.cache/huggingface
