annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.6.2
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Chevereto is an image hosting software that allows you to create a beautiful and full-featured image hosting website on your own server.
home: https://truecharts.org/charts/stable/chevereto
icon: https://truecharts.org/img/hotlink-ok/chart-icons/chevereto.webp
keywords:
  - chevereto
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: chevereto
sources:
  - https://chevereto-free.github.io/setup/stable/environment.html#image-handling-variables
  - https://ghcr.io/rodber/chevereto-free
  - https://github.com/rodber/chevereto-free
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/chevereto
type: application
version: 18.20.1

