annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: backup
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.14.1
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Web-accessible backup solution built on top of restic.
home: https://truecharts.org/charts/stable/backrest
icon: https://truecharts.org/img/hotlink-ok/chart-icons/backrest.webp
keywords:
  - backrest
  - backup
  - restic
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: backrest
sources:
  - https://github.com/garethgeorge/backrest
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/backrest
  - https://hub.docker.com/r/garethgeorge/backrest
type: application
version: 2.12.1

