annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.5.3
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: Papermerge is an open source document management system (DMS) primarily designed for archiving and retrieving your digital documents.
home: https://truecharts.org/charts/stable/papermerge
icon: https://truecharts.org/img/hotlink-ok/chart-icons/papermerge.webp
keywords:
  - papermerge
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: papermerge
sources:
  - https://github.com/ciur/papermerge
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/papermerge
  - https://hub.docker.com/r/papermerge/papermerge
type: application
version: 20.19.0

