annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: system
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 18.21.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Magical shell history.
home: https://truecharts.org/charts/stable/atuin
icon: https://truecharts.org/img/hotlink-ok/chart-icons/atuin.webp
keywords:
  - atuin
  - shell
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: atuin
sources:
  - https://ghcr.io/atuinsh/atuin
  - https://github.com/atuinsh/atuin
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/atuin
type: application
version: 7.19.0

