# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/doplarr
  tag: "3.8.0@sha256:997fe442e663f1f191edbf63cd55abe9a230a25907e46964bd59ef77a1daa8cc"
  pullPolicy: IfNotPresent
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            OVERSEERR__URL: ""
            DISCORD__MAX_RESULTS: 25
            DISCORD__REQUESTED_MSG_STYLE: ":plain"
            SONARR__URL: ""
            SONARR__QUALITY_PROFILE: ""
            SONARR__LANGUAGE_PROFILE: ""
            RADARR__URL: ""
            RADARR__QUALITY_PROFILE: ""
            PARTIAL_SEASONS: true
            LOG_LEVEL: ":info"
            OVERSEERR__API: ""
            OVERSEERR__DEFAULT_ID: ""
            SONARR__API: ""
            RADARR__API: ""
            DISCORD__ROLE_ID: ""
            DISCORD__TOKEN: ""
