annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.16.1
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Flood is a monitoring service for various torrent clients
home: https://truecharts.org/charts/stable/flood
icon: https://truecharts.org/img/hotlink-ok/chart-icons/flood.webp
keywords:
  - flood
  - rtorrent
  - qbittorrent
  - transmission
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: flood
sources:
  - https://github.com/jesec/flood
  - https://github.com/trueforge-org/containers/tree/main/apps/flood
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/flood
type: application
version: 17.13.1

