# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/flood
  pullPolicy: IfNotPresent
  tag: "4.16.1@sha256:4c8b2c8e808eb0a60b934f087ce9ec1e8f28b549165c7db7d9354b8bf7bafca5"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
persistence:
  data:
    enabled: true
    mountPath: /data
  config:
    enabled: true
    mountPath: /config
