#!/usr/bin/python3
import json
import re
import sys

from catalog_update.upgrade_strategy import semantic_versioning


RE_STABLE_VERSION = re.compile(r'[0-9]\.[0-9]\.[0-9]')


def newer_mapping(image_tags):
    key = list(image_tags.keys())[0]
    tags = {t: t for t in image_tags[key] if RE_STABLE_VERSION.fullmatch(t)}
    version = semantic_versioning(list(tags))
    if not version:
        return {}

    return {
        'tags': {key: tags[version]},
        'app_version': version,
    }


if __name__ == '__main__':
    try:
        versions_json = json.loads(sys.stdin.read())
    except ValueError:
        raise ValueError('Invalid json specified')

    print(json.dumps(newer_mapping(versions_json)))
