annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: games
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 17.0.1
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: the self-hosted gaming platform for alternatively obtained games.
home: https://truecharts.org/charts/stable/gamevault-backend
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gamevault-backend.webp
keywords:
  - gamevault-backend
  - games
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: gamevault-backend
sources:
  - https://github.com/Phalcode/gamevault-backend
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/gamevault-backend
  - https://hub.docker.com/r/phalcode/gamevault-backend
type: application
version: 15.2.1

