annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.2.1
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Open source, self-hostable watched list
home: https://truecharts.org/charts/stable/watcharr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/watcharr.webp
keywords:
  - watcharr
  - media
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: watcharr
sources:
  - https://ghcr.io/sbondco/watcharr
  - https://github.com/sbondCo/Watcharr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/watcharr
type: application
version: 11.6.0

