image:
  repository: ghcr.io/linuxserver/grocy
  tag: 4.5.0@sha256:c0408e2070b35947e1b20b79f4a03cb2727e4f628d2ec4e0fbfac051b4093e61
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
