annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: network
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.3.1
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: |
  A CNI meta-plugin for multi-homed pods in Kubernetes
home: https://truecharts.org/charts/stable/multus-cni
icon: https://truecharts.org/img/hotlink-ok/chart-icons/multus-cni.webp
keywords:
  - cni
  - networking
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: multus-cni
sources:
  - https://ghcr.io/k8snetworkplumbingwg/multus-cni
  - https://ghcr.io/siderolabs/cni
  - https://github.com/k8snetworkplumbingwg/multus-cni
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/multus-cni
  - https://hub.docker.com/r/alpine/crane
type: application
version: 2.13.1

