annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: "057352e8"
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A lightweight portal to view & manage your HTPC apps without having to run anything more than a PHP enabled webserver
home: https://truecharts.org/charts/stable/muximux
icon: https://truecharts.org/img/hotlink-ok/chart-icons/muximux.webp
keywords:
  - muximux
  - htpc
  - manage
  - portal
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: muximux
sources:
  - https://ghcr.io/linuxserver/muximux
  - https://github.com/linuxserver/docker-muximux
  - https://github.com/mescon/Muximux
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/muximux
type: application
version: 14.10.0

