annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.107.79
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Free and open source, powerful network-wide ads & trackers blocking DNS server.
home: https://truecharts.org/charts/stable/adguard-home
icon: https://truecharts.org/img/hotlink-ok/chart-icons/adguard-home.webp
keywords:
  - adblock
  - adguard
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: adguard-home
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/adguard-home
  - https://hub.docker.com/r/adguard/adguardhome
type: application
version: 13.10.0

