annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Network-DNS
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A very simple DNS server to connect to DNS-over-HTTPS service. This is similar to my other Pihole-with-DoH Chart, without Pihole.
home: https://truecharts.org/charts/stable/dns-doh-companion
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dns-doh-companion.webp
keywords:
  - dns-doh-companion
  - Network-DNS
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: dns-doh-companion
sources:
  - https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/dns-doh-companion
  - https://hub.docker.com/r/testdasi/simple-dns-doh
type: application
version: 9.10.1

