image:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 0.37.0-ultra-lite@sha256:248cb9978e758d7c8404aaf38e02a8ac93ef51fb51faa175c9caaf550359e8c8
fatImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 0.37.0-fat@sha256:f163796b7f0926e639bd2b28109850704e961016c29742dad583cb2efcf3011e
fullImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 0.37.0@sha256:824eb570cfc7653ff15e411d597da8bbdc84182304cb6957b12f2713b8efa256
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18080
workload:
  main:
    podSpec:
      containers:
        main:
          # checkout the difference between the images.
          # https://github.com/Stirling-Tools/Stirling-PDF/blob/main/Version-groups.md
          imageSelector: image
          env:
            # enable to add login support
            DOCKER_ENABLE_SECURITY: false
            # uncomment to set the intial auth
            # default auth below
            # SECURITY_INITIALLOGIN_USERNAME: admin
            # SECURITY_INITIALLOGIN_PASSWORD: stirling
            # Download Calibre onto Stirling-PDF to enable PDF to/from book and advanced HTML conversion
            INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
            LANGS: en_US
persistence:
  configs:
    enabled: true
    mountPath: "/configs"
  tessdata:
    enabled: true
    mountPath: "/usr/share/tessdata"
  custom-files:
    enabled: true
    mountPath: "/customFiles"
  logs:
    enabled: true
    mountPath: "/logs"
portal:
  open:
    enabled: true
