annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 31.4.5
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Drawio is free online diagram software.
home: https://truecharts.org/charts/stable/drawio
icon: https://truecharts.org/img/hotlink-ok/chart-icons/drawio.webp
keywords:
  - drawio
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: drawio
sources:
  - https://github.com/jgraph/drawio
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/drawio
  - https://hub.docker.com/r/jgraph/drawio
type: application
version: 21.7.1

