annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.10.4
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Gaps searches through your Plex Server or local folders for all movies, then queries for known movies in the same collection.
home: https://truecharts.org/charts/stable/gaps
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gaps.webp
keywords:
  - gaps
  - plex
  - plex-media-server
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: gaps
sources:
  - https://github.com/JasonHHouse/gaps
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/gaps
  - https://hub.docker.com/r/housewrecker/gaps
type: application
version: 22.10.0

