annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 10.6.2
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Airsonic is a Free and Open Source community driven media server
home: https://truecharts.org/charts/stable/airsonic
icon: https://truecharts.org/img/hotlink-ok/chart-icons/airsonic.webp
keywords:
  - airsonic
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: airsonic
sources:
  - https://ghcr.io/linuxserver/airsonic
  - https://github.com/airsonic/airsonic
  - https://github.com/k8s-at-home/charts/tree/master/charts/airsonic
  - https://github.com/linuxserver/docker-airsonic
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/airsonic
type: application
version: 17.10.1

