annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: home-automation
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.0.22
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Eclipse Mosquitto - An open source MQTT broker
home: https://truecharts.org/charts/stable/mosquitto
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mosquitto.webp
keywords:
  - mosquitto
  - home-automation
  - MQTT
  - eclipse-iot
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: mosquitto
sources:
  - https://github.com/eclipse/mosquitto
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/mosquitto
  - https://hub.docker.com/_/eclipse-mosquitto
type: application
version: 18.10.0

