annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.11.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Teedy is an open source, lightweight document management system for individuals and businesses.
home: https://truecharts.org/charts/stable/teedy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/teedy.webp
keywords:
  - teedy
  - documents
  - management
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: teedy
sources:
  - https://github.com/sismics/docs
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/teedy
  - https://hub.docker.com/r/sismics/docs
type: application
version: 19.10.1

