annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.136.1
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Run VS Code on any machine anywhere and access it in the browser.
home: https://truecharts.org/charts/stable/code-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/code-server.webp
keywords:
  - code
  - vs
  - visual studio
  - vscode
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: code-server
sources:
  - https://github.com/cdr/code-server
  - https://github.com/trueforge-org/containers/tree/main/apps/code-server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/code-server
type: application
version: 15.24.1

