# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/code-server
  pullPolicy: IfNotPresent
  tag: "4.136.1@sha256:1c07e8bc1a8079c7523a945463ab6c17079a0eae4fcd0d62080f2a84ad28e627"
securityContext:
  container:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10063
        protocol: http
        targetPort: 8443
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            PROXY_DOMAIN: ""
          args:
            - --user-data-dir
            - "/config/.vscode"
            - --auth
            - none
persistence:
  config:
    enabled: true
    mountPath: /config
