annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 11.1.4
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Airsonic is a Free and Open Source community driven media server
home: https://truecharts.org/charts/stable/airsonic-advanced
icon: https://truecharts.org/img/hotlink-ok/chart-icons/airsonic-advanced.webp
keywords:
  - airsonic
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: airsonic-advanced
sources:
  - https://github.com/airsonic/airsonic-advanced
  - https://github.com/trueforge-org/containers/tree/main/apps/airsonic-advanced
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/airsonic-advanced
type: application
version: 17.10.0

