# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/rflood
  tag: latest@sha256:355ef4d575e54293b104c004c5292959ba6c8b5a7f524c81d24ad88d07a9db2e
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: http
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_AUTH: "false"
