annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.35.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: true
description: Overseerr is a free and open source software application for managing requests for your media library. It integrates with your existing services such as Sonarr, Radarr and Plex!
home: https://truecharts.org/charts/stable/overseerr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/overseerr.webp
keywords:
  - overseerr
  - plex
  - sonarr
  - radarr
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: overseerr
sources:
  - https://ghcr.io/sct/overseerr
  - https://github.com/sct/overseerr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/overseerr
type: application
version: 18.6.0

