annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: cloud
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 34.0.3
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: A private cloud server that puts the control and security of your own data back into your hands.
home: https://truecharts.org/charts/stable/nextcloud
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nextcloud.webp
keywords:
  - nextcloud
  - storage
  - http
  - web
  - php
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: nextcloud
sources:
  - https://github.com/nextcloud/docker
  - https://github.com/nextcloud/helm
  - https://github.com/trueforge-org/containers/tree/main/apps/nextcloud-fpm
  - https://github.com/trueforge-org/containers/tree/main/apps/nextcloud-imaginary
  - https://github.com/trueforge-org/containers/tree/main/apps/nextcloud-notify-push
  - https://github.com/trueforge-org/containers/tree/main/apps/nginx
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/nextcloud
  - https://github.com/trueforge/truecharts/tree/master/charts/stable/nextcloud
  - https://hub.docker.com/r/clamav/clamav
  - https://hub.docker.com/r/collabora/code
type: application
version: 46.10.1

