annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: AI
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.33.3
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Get up and running with large language models locally.
home: https://truecharts.org/charts/stable/ollama
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ollama.webp
keywords:
  - ollama
  - language-models
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: ollama
sources:
  - https://ghcr.io/open-webui/open-webui
  - https://github.com/ollama/ollama
  - https://github.com/open-webui/open-webui
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/ollama
  - https://hub.docker.com/r/ollama/ollama
type: application
version: 9.30.0

