annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.6.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: The to-do app to organize your life.
home: https://truecharts.org/charts/stable/vikunja
icon: https://truecharts.org/img/hotlink-ok/chart-icons/vikunja.webp
keywords:
  - vikunja
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: vikunja
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/vikunja
  - https://hub.docker.com/r/vikunja/vikunja
  - https://vikunja.io/docs
type: application
version: 22.22.1

