annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: bookmarks
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.16.3
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Linkwarden is a self-hosted, open-source collaborative bookmark manager to collect, organize and archive webpages.
home: https://truecharts.org/charts/stable/linkwarden
icon: https://truecharts.org/img/hotlink-ok/chart-icons/linkwarden.webp
keywords:
  - linkwarden
  - bookmark
  - manager
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: linkwarden
sources:
  - https://ghcr.io/linkwarden/linkwarden
  - https://github.com/linkwarden/linkwarden
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/linkwarden
type: application
version: 8.13.2

