annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: games
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: An extensible, high performant & paralleled Minecraft proxy server.
home: https://truecharts.org/charts/stable/minecraft-gate
icon: https://truecharts.org/img/hotlink-ok/chart-icons/minecraft-gate.webp
keywords:
  - minecraft-gate
  - proxy
  - minecraft
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: minecraft-gate
sources:
  - https://ghcr.io/minekube/gate
  - https://github.com/minekube/gate
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/minecraft-gate
type: application
version: 3.10.0

