annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: stable
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A safe and private place for your life's work.
home: https://truecharts.org/charts/stable/standardnotes-web
icon: https://truecharts.org/img/hotlink-ok/chart-icons/standardnotes-web.webp
keywords:
  - standardnotes-web
  - Productivity
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: standardnotes-web
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/standardnotes-web
  - https://hub.docker.com/r/standardnotes/web
  - https://standardnotes.org/
type: application
version: 9.10.1

