annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: home-automation
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.08.00
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: backup all your tasmota devices in one place.
home: https://truecharts.org/charts/stable/tasmobackup
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tasmobackup.webp
keywords:
  - tasmobackup
  - home-automation
  - Network-Management
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: tasmobackup
sources:
  - https://github.com/danmed/TasmoBackupV1
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/tasmobackup
  - https://hub.docker.com/r/danmed/tasmobackupv1
type: application
version: 10.12.1

