annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Meta search engine which aggregates results from more than 70 search services.
home: https://truecharts.org/charts/stable/searxng
icon: https://truecharts.org/img/hotlink-ok/chart-icons/searxng.webp
keywords:
  - searxng
  - Productivity
  - Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: searxng
sources:
  - https://github.com/searxng/searxng
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/searxng
  - https://hub.docker.com/r/searxng/searxng
type: application
version: 11.10.0

