annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.100.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Dockerized Signal Messenger REST API.
home: https://truecharts.org/charts/stable/signal-cli-rest-api
icon: https://truecharts.org/img/hotlink-ok/chart-icons/signal-cli-rest-api.webp
keywords:
  - signal
  - signal-cli
  - api
  - rest-api
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: signal-cli-rest-api
sources:
  - https://github.com/bbernhard/signal-cli-rest-api
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/signal-cli-rest-api
  - https://hub.docker.com/r/bbernhard/signal-cli-rest-api
type: application
version: 2.12.1

