annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: custom
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.2.123
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Improved version of the OpenWebRX online SDR
home: https://truecharts.org/charts/stable/openwebrxplus
icon: https://truecharts.org/img/hotlink-ok/chart-icons/openwebrxplus.webp
keywords:
  - radio
  - sdr
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: openwebrxplus
sources:
  - https://github.com/luarvique/openwebrx
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/openwebrxplus
  - https://hub.docker.com/r/slechev/openwebrxplus-softmbe
type: application
version: 3.10.1

