annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: GameServers
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: This Chart will download and install the version of OpenTTD that you enter in the variable 'GAME_VERSION' (if you define 'latest' it will always pull the latest build, if you define 'testing' it will always pull down the latest testing build).
home: https://truecharts.org/charts/stable/openttd
icon: https://truecharts.org/img/hotlink-ok/chart-icons/openttd.webp
keywords:
  - openttd
  - GameServers
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: openttd
sources:
  - https://ghcr.io/ich777/openttdserver
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/openttd
  - https://www.openttd.org/
type: application
version: 9.10.0

