annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: inventory
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.26.1
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Keep track of your inventory of 3D-printer filament spools.
home: https://truecharts.org/charts/stable/spoolman
icon: https://truecharts.org/img/hotlink-ok/chart-icons/spoolman.webp
keywords:
  - spoolman
  - inventory
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: spoolman
sources:
  - https://ghcr.io/donkie/spoolman
  - https://github.com/Donkie/Spoolman
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/spoolman
type: application
version: 2.13.1

