annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Backup
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: This application backs up every folder mounted at `/data/` to a given AWS S3 path using the `aws s3 sync` command. It requires a pair of (IAM) Access and Secret Keys.
home: https://truecharts.org/charts/stable/s3sync
icon: https://truecharts.org/img/hotlink-ok/chart-icons/s3sync.webp
keywords:
  - s3sync
  - Backup
  - Cloud
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: s3sync
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/s3sync
  - https://github.com/what-name/docker-s3sync
  - https://hub.docker.com/r/whatname/docker-s3sync
type: application
version: 9.10.0

