annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: social
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.05.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.9.1
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.9.2
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: Welcome to the free social web
home: https://truecharts.org/charts/stable/friendica
icon: https://truecharts.org/img/hotlink-ok/chart-icons/friendica.webp
keywords:
  - friend
  - social
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: friendica
sources:
  - https://friendi.ca/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/friendica
  - https://hub.docker.com/_/friendica
type: application
version: 23.21.0

