annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.10.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Pylon is a web based integrated development environment.
home: https://truecharts.org/charts/stable/pylon
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pylon.webp
keywords:
  - pylon
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pylon
sources:
  - https://ghcr.io/linuxserver/pylon
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/pylon
type: application
version: 13.10.1

