annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Downloaders
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.1.0.2116
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: An adult media thingy.
home: https://truecharts.org/charts/stable/whisparr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/whisparr.webp
keywords:
  - whisparr
  - Downloaders
  - MediaApp-Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: whisparr
sources:
  - https://ghcr.io/hotio/whisparr
  - https://github.com/onedr0p/containers/tree/main/apps/whisparr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/whisparr
type: application
version: 15.10.0

