annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.43.3.10896
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Plex Media Server
home: https://truecharts.org/charts/stable/plex
icon: https://truecharts.org/img/hotlink-ok/chart-icons/plex.webp
keywords:
  - plex
  - plex-media-server
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: plex
sources:
  - https://github.com/k8s-at-home/container-images/pkgs/container/plex
  - https://github.com/trueforge-org/containers/tree/main/apps/plex
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/plex
type: application
version: 22.10.1

