annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Backup
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 6.12.5040
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Sourcegraph Chart.
home: https://truecharts.org/charts/stable/sourcegraph
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sourcegraph.webp
keywords:
  - sourcegraph
  - Backup
  - Cloud
  - Network-Web
  - Productivity
  - Tools-Utilities
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: sourcegraph
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/sourcegraph
  - https://hub.docker.com/r/sourcegraph/server
type: application
version: 10.10.1

