image:
  pullPolicy: IfNotPresent
  repository: docker.io/sourcegraph/server
  tag: 5.11.4013@sha256:355bfecb6d2344f335204a215ccf4ca5029842bcbad19dfeb562f6e4c90dc94a
persistence:
  applicationdatastoragepath:
    enabled: true
    mountPath: /var/opt/sourcegraph
  configstoragepath:
    enabled: true
    mountPath: /etc/sourcegraph
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  adminconsolepo:
    enabled: true
    ports:
      adminconsolepo:
        enabled: true
        port: 2633
        protocol: tcp
        targetPort: 2633
  grafanaport:
    enabled: true
    ports:
      grafanaport:
        enabled: true
        port: 3370
        protocol: tcp
        targetPort: 3370
  main:
    ports:
      main:
        port: 7080
        protocol: http
        targetPort: 7080
