annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 5.6.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: TileServer GL is a server for raster and vector map tiles, supporting MBTiles, PBF vector tiles and GL styles.
home: https://truecharts.org/charts/stable/tileserver-gl
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tileserver-gl.webp
keywords:
  - tileserver-gl
  - maps
  - tiles
  - mbtiles
  - vector-tiles
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: tileserver-gl
sources:
  - https://github.com/maptiler/tileserver-gl
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/tileserver-gl
  - https://hub.docker.com/r/maptiler/tileserver-gl
type: application
version: 1.0.1

