annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.109.5
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Openvscode-server provides a version of VS Code that runs a server on a remote machine.
home: https://truecharts.org/charts/stable/openvscode-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/openvscode-server.webp
keywords:
  - openvscode-server
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: openvscode-server
sources:
  - https://ghcr.io/linuxserver/openvscode-server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/openvscode-server
type: application
version: 13.10.0

