annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.5.2
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: FlareSolverr is a proxy server to bypass Cloudflare protection
home: https://truecharts.org/charts/stable/flaresolverr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/flaresolverr.webp
keywords:
  - flaresolverr
  - proxy
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: flaresolverr
sources:
  - https://ghcr.io/flaresolverr/flaresolverr
  - https://github.com/FlareSolverr/FlareSolverr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/flaresolverr
type: application
version: 17.11.1

