annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Cloud
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.1.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A dead simple URL shortener.
home: https://truecharts.org/charts/stable/simply-shorten
icon: https://truecharts.org/img/hotlink-ok/chart-icons/simply-shorten.webp
keywords:
  - simply-shorten
  - Cloud
  - Productivity
  - Network-Web
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: simply-shorten
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/simply-shorten
  - https://gitlab.com/draganczukp/simply-shorten
  - https://hub.docker.com/r/draganczukp/simply-shorten
type: application
version: 12.10.1

