annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.6.15
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Tandoor Recipes is a Django application to manage, tag and search recipes using either built in models or external storage providers hosting PDF's, Images or other files.
home: https://truecharts.org/charts/stable/tandoor-recipes
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tandoor-recipes.webp
keywords:
  - tandoor
  - recipes
  - cooking
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: tandoor-recipes
sources:
  - https://ghcr.io/tandoorrecipes/recipes
  - https://github.com/TandoorRecipes/recipes
  - https://github.com/TandoorRecipes/recipes/pkgs/container/recipes
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/tandoor-recipes
type: application
version: 21.11.0

