annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.87.01
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Audio/Video library transcoding automation
home: https://truecharts.org/charts/stable/tdarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tdarr.webp
keywords:
  - encode
  - media
  - tdarr
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: tdarr
sources:
  - https://github.com/HaveAGitGat/Tdarr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/tdarr
  - https://github.com/trueforge/truecharts/tree/master/charts/stable/tdarr
  - https://hub.docker.com/r/haveagitgat/tdarr
type: application
version: 13.33.0

