# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/webgrabplus
  pullPolicy: IfNotPresent
  tag: 5.6.1@sha256:ddf2b93738df3cad8b927f686c8d60db389d1326679a3987739f394f4d6ce2fb
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
