annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.4.5
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Rsnapshot is a filesystem snapshot utility based on rsync.
home: https://truecharts.org/charts/stable/rsnapshot
icon: https://truecharts.org/img/hotlink-ok/chart-icons/rsnapshot.webp
keywords:
  - rsnapshot
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: rsnapshot
sources:
  - https://ghcr.io/linuxserver/rsnapshot
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/rsnapshot
type: application
version: 13.10.2

