annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: networking
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.22.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
home: https://truecharts.org/charts/stable/external-dns
icon: https://truecharts.org/img/hotlink-ok/chart-icons/external-dns.webp
keywords:
  - external-dns
  - k8s
  - kubernetes
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: external-dns
sources:
  - https://github.com/kubernetes-sigs/external-dns
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/external-dns
type: application
version: 8.12.1

