annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: backup
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.8.8
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A borg Backup server
home: https://truecharts.org/charts/stable/borg-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/borg-server.webp
keywords:
  - borg-server
  - backup
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: borg-server
sources:
  - https://ghcr.io/anotherstranger/borg-server
  - https://github.com/AnotherStranger/docker-borg-backup
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/borg-server
type: application
version: 8.10.1

