annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Other
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.2.5
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Google Photos Sync downloads your Google Photos to the local file system. It will backup all the photos the user uploaded to Google Photos, but also the album information and additional Google Photos 'Creations' (animations, panoramas, movies, effects and collages).
home: https://truecharts.org/charts/stable/googlephotossync
icon: https://truecharts.org/img/hotlink-ok/chart-icons/googlephotossync.webp
keywords:
  - googlephotossync
  - Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: googlephotossync
sources:
  - https://ghcr.io/gilesknap/gphotos-sync
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/googlephotossync
type: application
version: 10.10.0

