annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: learning
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.8.7
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: CTFd is a Capture The Flag framework focusing on ease of use and customizability.
home: https://truecharts.org/charts/stable/ctfd
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ctfd.webp
keywords:
  - ctfd
  - learning
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: ctfd
sources:
  - https://ghcr.io/ctfd/ctfd
  - https://github.com/CTFd/CTFd
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/ctfd
type: application
version: 13.19.1

