annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: metrics
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 5.2.5
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Collect your UniFi controller data and report it to an InfluxDB instance, or export it for Prometheus collection.
home: https://truecharts.org/charts/stable/unpoller
icon: https://truecharts.org/img/hotlink-ok/chart-icons/unpoller.webp
keywords:
  - unifi
  - unifi-poller
  - metrics
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: unpoller
sources:
  - https://ghcr.io/unpoller/unpoller
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/unpoller
  - https://github.com/unifi-poller/unifi-poller
type: application
version: 17.3.1

