annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: web-server
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.44.0
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A cross-platform, high-performance and asynchronous web server for static files-serving.
home: https://truecharts.org/charts/stable/static-web-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/static-web-server.webp
keywords:
  - web-server
  - apache
  - rust
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: static-web-server
sources:
  - https://ghcr.io/static-web-server/static-web-server
  - https://github.com/static-web-server/static-web-server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/static-web-server
  - https://static-web-server.net
type: application
version: 8.12.1

