annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.85.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: The modern download automation tool for torrents.
home: https://truecharts.org/charts/stable/autobrr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/autobrr.webp
keywords:
  - autobrr
  - torrent
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: autobrr
sources:
  - https://ghcr.io/autobrr/autobrr
  - https://github.com/autobrr/autobrr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/autobrr
type: application
version: 12.21.0

