# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/autobrr/autobrr
  pullPolicy: IfNotPresent
  tag: v1.86.0@sha256:0b8b997c40424557a4bd688a4cb487dd8a765a69b5aa5b003c0d8106f6a895af

service:
  main:
    ports:
      main:
        protocol: http
        port: 7474

autobrr:
  # ERROR | DEBUG |INFO | WARN | TRACE
  log_level: DEBUG

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /config
  autobrr-config:
    enabled: true
    type: configmap
    objectName: autobrr-config
    mountPath: /config/config.toml
    subPath: config.toml
    readOnly: true
