annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Tools-Utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Self Hosted, self contained New Year Countdown clock
home: https://truecharts.org/charts/stable/newyearcountdownclock
icon: https://truecharts.org/img/hotlink-ok/chart-icons/newyearcountdownclock.webp
keywords:
  - newyearcountdownclock
  - Tools-Utilities
  - Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: newyearcountdownclock
sources:
  - https://github.com/modem7/Docker-NewYearCountdown
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/newyearcountdownclock
  - https://hub.docker.com/r/modem7/newyearcountdown
type: application
version: 9.10.1

