# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/xavierh/external-ip
  tag: latest@sha256:eae953728e95a9536d0c85b941bbc55b66c64f62713402bd8f1d182073b921a8
persistence: {}

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DELAY: 5m
            NOTIFICATION_TYPE: ""
            PROVIDER: ""
            PUSHOVER_TITLE: ""
            PUSHOVER_TOKEN: ""
            PUSHOVER_USER: ""
            RECOVERY_ALERT: ""
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
