# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/nzbhydra2
  pullPolicy: IfNotPresent
  tag: 8.9.0@sha256:ec1a07c58743dfbbe37b631f60dd606c8fde6285313f1c4428f7690c6f525852
service:
  main:
    ports:
      main:
        port: 5076
        targetPort: 5076
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/livenessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            readiness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            startup:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
