image:
  repository: ghcr.io/elfhosted/nzbhydra2
  pullPolicy: IfNotPresent
  tag: 7.15.0@sha256:a9b7cc4fb15c5b2bece15cffbecf33c91502a12b25b3e6d954e993ce2c946e33
service:
  main:
    ports:
      main:
        port: 5076
        targetPort: 5076
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/livenessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            readiness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            startup:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
