annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.5.12
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: ByteStash is a self-hosted web application designed to store, organise, and manage your code snippets efficiently. With support for creating, editing, and filtering snippets, ByteStash helps you keep track of your code in one secure place.
home: https://truecharts.org/charts/stable/bytestash
icon: https://truecharts.org/img/hotlink-ok/chart-icons/bytestash.webp
keywords:
  - bytestash
  - Productivity
  - Tools-Utilities
  - code
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: bytestash
sources:
  - https://ghcr.io/jordan-dalby/bytestash
  - https://github.com/jordan-dalby/ByteStash
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/bytestash
type: application
version: 3.10.1

