annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.3.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Take control over your live stream video by running it yourself. Streaming + chat out of the box.
home: https://truecharts.org/charts/stable/owncast
icon: https://truecharts.org/img/hotlink-ok/chart-icons/owncast.webp
keywords:
  - owncast
  - stream
  - open source
  - chat
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: owncast
sources:
  - https://github.com/owncast/owncast
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/owncast
  - https://hub.docker.com/r/gabekangas/owncast
  - https://owncast.online/
type: application
version: 17.11.1

