#!/usr/bin/python3
import json
import sys

from catalog_update.upgrade_strategy import semantic_versioning


def newer_mapping(image_tags):
    key = list(image_tags.keys())[0]
    version = semantic_versioning(image_tags[key])
    if not version:
        return {}

    return {
        'tags': {key: f'v{version}'},
        'app_version': f'v{version}',
    }


if __name__ == '__main__':
    try:
        versions_json = json.loads(sys.stdin.read())
    except ValueError:
        raise ValueError('Invalid json specified')

    print(json.dumps(newer_mapping(versions_json)))
