image:
  repository: fyb3roptik/threadfin
  tag: 1.2.24@sha256:cdc8f8d4e50d95c318e32b026a196f41bd8cca4a40c93b35e321bed8c4c42dbc
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 34400
persistence:
  config:
    enabled: true
    mountPath: "/home/threadfin/conf"
  temp:
    enabled: true
    mountPath: "/tmp/threadfin"
    type: emptyDir
portal:
  open:
    enabled: true
