annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Serial to Socket Redirector
home: https://truecharts.org/charts/stable/ser2sock
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ser2sock.webp
keywords:
  - ser2sock
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: ser2sock
sources:
  - https://github.com/nutechsoftware/ser2sock
  - https://github.com/tenstartups/ser2sock
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/ser2sock
  - https://hub.docker.com/r/tenstartups/ser2sock
type: application
version: 17.10.0

