annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: emulator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.9.2
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Emulatorjs - In browser web based emulation portable to nearly any device for many retro consoles.
home: https://truecharts.org/charts/stable/emulatorjs
icon: https://truecharts.org/img/hotlink-ok/chart-icons/emulatorjs.webp
keywords:
  - emulatorjs
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: emulatorjs
sources:
  - https://ghcr.io/linuxserver/emulatorjs
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/emulatorjs
type: application
version: 13.10.1

