annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Tools-Utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: DIY tool to create and print labels for Dell Poweredge and HP Proliant drive caddies.
home: https://truecharts.org/charts/stable/homelablabelmaker
icon: https://truecharts.org/img/hotlink-ok/chart-icons/homelablabelmaker.webp
keywords:
  - homelablabelmaker
  - Tools-Utilities
  - Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: homelablabelmaker
sources:
  - https://github.com/DavidSpek/homelablabelmaker
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/homelablabelmaker
  - https://hub.docker.com/r/davidspek/homelablabelmaker
type: application
version: 12.10.1

