annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: business
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.2.4
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Open source DocuSign alternative. Create, fill, and sign digital documents.
home: https://truecharts.org/charts/stable/docuseal
icon: https://truecharts.org/img/hotlink-ok/chart-icons/docuseal.webp
keywords:
  - docuseal
  - business
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: docuseal
sources:
  - https://github.com/docusealco/docuseal
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/docuseal
  - https://hub.docker.com/r/docuseal/docuseal
type: application
version: 7.9.1

