# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/znc
  pullPolicy: IfNotPresent
  tag: 1.10.2@sha256:39a2f84a8376cb71bdb969447cff4e8ffa953ff618f9c5cda9b67b14d3bf6d1d
service:
  main:
    ports:
      main:
        targetPort: 6501
        port: 6501
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
