annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Network
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: This is a Basic STUN & TURN server that was mainly created for Nextcloud Talk.
home: https://truecharts.org/charts/stable/stun-turn-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/stun-turn-server.webp
keywords:
  - stun-turn-server
  - Network
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: stun-turn-server
sources:
  - https://ghcr.io/ich777/stun-turn-server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/stun-turn-server
type: application
version: 10.10.1

