annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: metrics
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.5.4
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Speedtest Exporter made in python using the official speedtest bin
home: https://truecharts.org/charts/stable/speedtest-exporter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/speedtest-exporter.webp
keywords:
  - speedtest-exporter
  - speedtest
  - metrics
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: speedtest-exporter
sources:
  - https://ghcr.io/miguelndecarvalho/speedtest-exporter
  - https://github.com/MiguelNdeCarvalho/speedtest-exporter/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/speedtest-exporter
type: application
version: 14.10.1

