annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: docker
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 29.8.0
dependencies:
  - name: common
    version: 29.17.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Dedicated App for using Docker-in-Docker
home: https://truecharts.org/charts/stable/docker
icon: https://truecharts.org/img/hotlink-ok/chart-icons/docker.webp
keywords:
  - docker
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: docker
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/docker
  - https://hub.docker.com/_/docker
type: application
version: 13.14.0

