# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:49a08b1e871aa300829d206141dc932459c7db2866269120ad79ec9d959ccbed
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:1bd141d5d7aaf3e98e47b7d9665f50657d1628617b4ef47bc3bbd43d726fd77e
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:cb44a80dc03a72bb80b8cef512ff8155028e0f76df5fb696e5196a654090ef57
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:4fe0d26b9b5808606f31dc223dfdddfa847fc06e1bf68ca8598e642376bbed4b
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:1df1c8f99bbb269549de44b4d37a779455741668696bfe61110471fe84e9219b
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:22992f42e533771824184b7e0f740f28f7d4ed988558fdb8a33201350979d45e
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:3eca8a18479d48be0ce2b9e4246475b7fd73a5ab11a75477103a78fec461c960
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:ed197a60c161b5d45a0d0137a5c47ecd136964c57791bf3151d01ad41ac6b988
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:88b75806a58aab4faec73e7f805e7685c91d641e411a7f5e6195329c14004482
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:dd6b8c06e03da3a0fa34c3abb719486fbd47d2db710b272ab2a5de149e5d33f5
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:d02605dffe9f5792f35a14ed659385915f0acddb0e3b9f37d703cdc10166561c
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:038c3465d966c9e6ed6ec30283fba94edc0b794cd91bbb86108bd86b36da4797
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:9b36d68534edd6b7a47b89e7db5f036ad9855f712120214e6e9ed285ec7bfba7
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:003582036adb92b173754f113da441aa3fea31d5f552f0bbfb7dac7da8a3518a
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:fe112c6a27acd55861f54aefb7a585dc49c1dc146faf8d7ae446991d610bcf3b
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:3c12974952348cebe8e08b6940a8c483112a528396fb21b04dd176e2eb196b3f
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:32d2f78a5d2359569c8a625d080ed53ecead477ccca707c55c1afc9c6e0765f9
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:539248133c65e3d2d70dff67c8f9ff297186615487972491451210b1b9ee4d71
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:c40f887d9c03c5966debdfb8d9a6fb1a446cd5cb5dadde6195ca35a068742409
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:7f079e913b5696455889f795aff7c3acea1ab581de313ec63a797604c805d12d
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:440aebeafa9b9101d03f633be9a504d75917fcb7d6847842f67aa033c46f06f3
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:26f960e120edc080a12dfd76944acae0296eb7b69d79c437ef329836cc09e47a
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:871a0acf70fb754216f11b0c98fec51ab6871fc00f12a9a20eae0202cf7b1644
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:54d9079d38aee34063206fb5b233ea7c8801108756fb61aa0680eabdfad91dcd
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
