image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:0d7d39b5a9a307d5fa32da1fde4e213cfaba7e41dc0aad47845231692be7ab68
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:d3c8f640dad0ba5c8547d7e26de933258d300db4650855ccaa25fdeec0078ba5
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:07efbcda064f8bfae2196b22ef3e47e8a95a6cc02237c8fcb0965aee19b717be
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:0cce2a9987de6c79ced884fcabc3f77d1a418c8e70c16ac6a61ade2559450f4a
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:d4e5479380a81da35dc28445a550b4b436798a1b5c59af7eabce3e261e0b010b
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:2186b3a9e2cbf838b5d8cd1b6d1d3d85aaf3af3cdbf90818a7c68d62f1aaae4d
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:0b0f4e26c0c6cbe06f9cc4ae011a375f38990af8ed0dc4da1fc2b967e7507840
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:85ab4408a73636a6864c1216e291184d5cc7b07fe962259e24334ee68c9d7550
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:96f25f286aa2cd38b6d46019fa070e2b59f0bc5fa988351f37bb731ce517a6fc
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:f11d869b7c5989f5ebd3b437a3c524ee2ca770620cd5ad1e75e843b626046b06
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:78f9c6583f7bc7a6b55f78cb7e72b596e8d3f6007e9799708a4b3c91e38e7e53
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:b12603e40e2a0def694fa5be0954f009c59acb9a751fee333148fba2a0f8c651
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:c4c82c4a66994c316fdc58abdfcc02722e2f48be6b0725471be459dc92296692
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:1e8814a7d554e3138d635f52a5d3f98297739b5d2f0bb16a3855544f889f4f64
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:948eaadd31f5d278dd9bc41c21d2be1cf35a3446068b164c0a00e9c97445bb19
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:cb99a34c09a4c8e824c4feb760a09c082b643c79a56e2f23c955830e766bb87f
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:32d2f78a5d2359569c8a625d080ed53ecead477ccca707c55c1afc9c6e0765f9
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:539248133c65e3d2d70dff67c8f9ff297186615487972491451210b1b9ee4d71
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:c40f887d9c03c5966debdfb8d9a6fb1a446cd5cb5dadde6195ca35a068742409
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:7f079e913b5696455889f795aff7c3acea1ab581de313ec63a797604c805d12d
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:440aebeafa9b9101d03f633be9a504d75917fcb7d6847842f67aa033c46f06f3
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:26f960e120edc080a12dfd76944acae0296eb7b69d79c437ef329836cc09e47a
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:871a0acf70fb754216f11b0c98fec51ab6871fc00f12a9a20eae0202cf7b1644
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:54d9079d38aee34063206fb5b233ea7c8801108756fb61aa0680eabdfad91dcd
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
