annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: monitoring
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 5.36.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Automated service health dashboard
home: https://truecharts.org/charts/stable/gatus
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gatus.webp
keywords:
  - gatus
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: gatus
sources:
  - https://ghcr.io/home-operations/gatus-sidecar
  - https://ghcr.io/twin/gatus
  - https://github.com/TwiN/gatus
  - https://github.com/home-operations/gatus-sidecar
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/gatus
type: application
version: 4.16.1

