annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: database
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mongodb
    version: 17.10.1
    repository: oci://oci.trueforge.org/truecharts
    condition: mongodb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: mongo-express is a web-based MongoDB admin interface written in Node.js, Express.js, and Bootstrap3.
home: https://truecharts.org/charts/stable/mongo-express
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mongo-express.webp
keywords:
  - mongo
  - mongodb
  - database
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: mongo-express
sources:
  - https://gallery.ecr.aws/docker/library/mongo-express
  - https://github.com/mongo-express/mongo-express
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/mongo-express
type: application
version: 11.20.1

