annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: games
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.8.2
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Minecraft Bedrock Dedicated Server
home: https://truecharts.org/charts/stable/minecraft-bedrock
icon: https://truecharts.org/img/hotlink-ok/chart-icons/minecraft-bedrock.webp
keywords:
  - minecraft
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: minecraft-bedrock
sources:
  - https://ghcr.io/itzg/minecraft-bedrock-server
  - https://github.com/itzg/docker-minecraft-server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/minecraft-bedrock
type: application
version: 14.15.0

