# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/mstream
  pullPolicy: IfNotPresent
  tag: 6.26.0@sha256:0384a8a94d8bb894da9715ce1c155789ddd29659d1ac3a8f61bfd959c57245a3
service:
  main:
    ports:
      main:
        port: 10041
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
