annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.4.2
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Orca Slicer is an open source slicer for FDM printers.
home: https://truecharts.org/charts/stable/orcaslicer
icon: https://truecharts.org/img/hotlink-ok/chart-icons/orcaslicer.webp
keywords:
  - orcaslicer
  - 3d
  - printer
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: orcaslicer
sources:
  - https://ghcr.io/linuxserver/orcaslicer
  - https://github.com/SoftFever/OrcaSlicer
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/orcaslicer
type: application
version: 3.11.0

