image:
  repository: docker.io/foxxmd/multi-scrobbler
  tag: latest@sha256:ab4589aaf3c5de9cc7113b9aa97bc33b11119a6564abf413fb426ae895bbb122
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 9078
        targetPort: 9078

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
