annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Network-Web
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Chart to provide a DDNS service for godaddy domains. Uses the GoDaddy REST API to update the given domain's DNS IP address to the public IP address of the host it is executing on. Performs a check every 10 minutes, but you can alter this if you like by modifying /etc/cron.d/godaddy-ddns inside the Chart.
home: https://truecharts.org/charts/stable/godaddy-ddns
icon: https://truecharts.org/img/hotlink-ok/chart-icons/godaddy-ddns.webp
keywords:
  - godaddy-ddns
  - Network-Web
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: godaddy-ddns
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/godaddy-ddns
  - https://hub.docker.com/r/jwater7/godaddy-publicip-updater
type: application
version: 9.10.0

