annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: BUSL-1.1
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: library
  trueforge.org/category: unsorted
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: library
apiVersion: v2
appVersion: 1.12.0
dependencies: []
deprecated: false
description: Function library for TrueCharts
home: https://truecharts.org/charts/library/common
icon: https://truecharts.org/img/hotlink-ok/chart-icons/common.webp
keywords:
  - truecharts
  - library-chart
  - common
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: common
sources:
  - https://ghcr.io/cloudnative-pg/postgis
  - https://ghcr.io/cloudnative-pg/postgresql
  - https://ghcr.io/tensorchord/cloudnative-pgvecto.rs
  - https://ghcr.io/tensorchord/cloudnative-vectorchord
  - https://ghcr.io/traefik/whoami
  - https://github.com/trueforge-org/containers/tree/main/apps/code-server
  - https://github.com/trueforge-org/containers/tree/main/apps/go-yq
  - https://github.com/trueforge-org/containers/tree/main/apps/kubectl
  - https://github.com/trueforge-org/containers/tree/main/apps/mariadb-client
  - https://github.com/trueforge-org/containers/tree/main/apps/mongosh
  - https://github.com/trueforge-org/containers/tree/main/apps/postgresql-client
  - https://github.com/trueforge-org/containers/tree/main/apps/scratch
  - https://github.com/trueforge-org/containers/tree/main/apps/ubuntu
  - https://github.com/trueforge-org/containers/tree/main/apps/valkey-tools
  - https://github.com/trueforge-org/truecharts/tree/master/charts/library/common
  - https://hub.docker.com/_/
type: library
version: 29.20.1

