annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 26.09.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: An application that lets you automatically process files through a simple rule flow.
home: https://truecharts.org/charts/stable/fileflows
icon: https://truecharts.org/img/hotlink-ok/chart-icons/fileflows.webp
keywords:
  - fileflows
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: fileflows
sources:
  - https://github.com/revenz/FileFlows
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/fileflows
  - https://hub.docker.com/r/revenz/fileflows
type: application
version: 16.16.1

