annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2021.11.21
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Ngircd is a free, portable and lightweight Internet Relay Chat server for small or private networks.
home: https://truecharts.org/charts/stable/ngircd
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ngircd.webp
keywords:
  - ngircd
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: ngircd
sources:
  - https://ghcr.io/linuxserver/ngircd
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/ngircd
type: application
version: 13.10.1

