annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.3.3
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Fleet provides an online web interface which displays a set of maintained images from one or more owned repositories.
home: https://truecharts.org/charts/stable/fleet
icon: https://truecharts.org/img/hotlink-ok/chart-icons/fleet.webp
keywords:
  - fleet
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: fleet
sources:
  - https://ghcr.io/linuxserver/fleet
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/fleet
type: application
version: 18.20.0

