annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: metrics
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.14.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Prometheus exporter for SMART using smartctl binary to gather metrics.
home: https://truecharts.org/charts/stable/smartctl-exporter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/smartctl-exporter.webp
keywords:
  - prometheus
  - smartctl-exporter
  - monitoring
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: smartctl-exporter
sources:
  - https://github.com/prometheus-community/smartctl_exporter
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/smartctl-exporter
  - https://hub.docker.com/r/prometheuscommunity/smartctl-exporter
type: application
version: 6.10.0

