annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: GameServers
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Urban Terror is a free multiplayer first person shooter developed by FrozenSand, that will run on any Quake III Arena compatible engine. It is available for Windows, Linux and Macintosh.
home: https://truecharts.org/charts/stable/urban-terror
icon: https://truecharts.org/img/hotlink-ok/chart-icons/urban-terror.webp
keywords:
  - urban-terror
  - GameServers
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: urban-terror
sources:
  - https://ghcr.io/ich777/urbanterror
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/urban-terror
  - https://www.urbanterror.info/
type: application
version: 9.10.0

