annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Alternative front-end for Google Translate, serving as a Free and Open Source translator with over a hundred languages available
home: https://truecharts.org/charts/stable/lingva
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lingva.webp
keywords:
  - lingva
  - Productivity
  - Tools-Utilities
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: lingva
sources:
  - https://github.com/TheDavidDelta/lingva-translate
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/lingva
  - https://hub.docker.com/r/thedaviddelta/lingva-translate
type: application
version: 9.10.1

