annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Downloaders
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.13.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: This tool will help manage tedious tasks in qBittorrent and automate them. Tag, categorize, remove orphaned data, remove unregistered torrents and much much more.
home: https://truecharts.org/charts/stable/qbitmanage
icon: https://truecharts.org/img/hotlink-ok/chart-icons/qbitmanage.webp
keywords:
  - qbitmanage
  - Downloaders
  - MediaApp-Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: qbitmanage
sources:
  - https://github.com/StuffAnThings/qbit_manage/wiki/Docker-Installation
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/qbitmanage
  - https://hub.docker.com/r/bobokun/qbit_manage
type: application
version: 12.17.0

