annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: tools
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2024.10.22
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Useful tools for developer and people working in IT.
home: https://truecharts.org/charts/stable/it-tools
icon: https://truecharts.org/img/hotlink-ok/chart-icons/it-tools.webp
keywords:
  - it-tools
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: it-tools
sources:
  - https://github.com/CorentinTh/it-tools
  - https://github.com/trueforge-org/containers/tree/main/apps/it-tools
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/it-tools
type: application
version: 9.10.1

