# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/it-tools
  pullPolicy: IfNotPresent
  tag: 2024.10.22@sha256:19894b6257b8a5b00f93bf2082ddaefee9f577e1fe45375cb3c132c9f15ccd6e
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18082
persistence:
  cache:
    enabled: true
    type: emptyDir
    mountPath: "/var/cache/nginx"
  config:
    enabled: true
    type: emptyDir
    mountPath: /config
