annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: finance
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 26.9.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Actual is a super fast privacy-focused app for managing your finances.
home: https://truecharts.org/charts/stable/actualserver
icon: https://truecharts.org/img/hotlink-ok/chart-icons/actualserver.webp
keywords:
  - actualserver
  - finance
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: actualserver
sources:
  - https://ghcr.io/actualbudget/actual
  - https://github.com/Kippenhof/docker-templates
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/actualserver
type: application
version: 16.16.1

