image:
  repository: docker.io/docuseal/docuseal
  tag: 1.8.7@sha256:c534e3a4c478c45eb72448dbd84514168a0058288a896bff76ee2c2b355184bc
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10310
        protocol: http
        targetPort: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /

persistence:
  data:
    enabled: true
    mountPath: /data

portal:
  open:
    enabled: true

cnpg:
  main:
    enabled: true
    user: docuseal
    database: docuseal
