annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 8.4.9
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Folding@home is a distributed computing project for simulating protein dynamics, including the process of protein folding and the movements of proteins implicated in a variety of diseases.
home: https://truecharts.org/charts/stable/foldingathome
icon: https://truecharts.org/img/hotlink-ok/chart-icons/foldingathome.webp
keywords:
  - foldingathome
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: foldingathome
sources:
  - https://github.com/trueforge-org/containers/tree/main/apps/foldingathome
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/foldingathome
type: application
version: 14.10.1

