annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.8.0
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A simple bookmark manager built with Go.
home: https://truecharts.org/charts/stable/shiori
icon: https://truecharts.org/img/hotlink-ok/chart-icons/shiori.webp
keywords:
  - shiori
  - bookmark
  - bookmark-manager
  - web-interface
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: shiori
sources:
  - https://ghcr.io/go-shiori/shiori
  - https://github.com/go-shiori/shiori
  - https://github.com/go-shiori/shiori/pkgs/container/shiori
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/shiori
type: application
version: 20.10.1

