annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: '&lt;b&gt;Barcode Buddy is a Grocy companion app/plugin, which allows you to install the Barcode Buddy app and scan products directly to your Grocy library.&lt;/b&gt;'
home: https://truecharts.org/charts/stable/barcodebuddy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/barcodebuddy.webp
keywords:
  - barcodebuddy
  - Productivity
  - Tools-Utilities
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: barcodebuddy
sources:
  - https://github.com/Forceu/barcodebuddy
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/barcodebuddy
  - https://hub.docker.com/r/f0rc3/barcodebuddy
type: application
version: 9.10.2

