# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/f0rc3/barcodebuddy
  tag: latest@sha256:07aa95c8c96bdd095fc1a361f40e7437e02e2b283978d5a1fb9e20d99ecaa70a
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8450
        protocol: tcp
        targetPort: 80
