#!/usr/bin/python3
import json
import sys

from catalog_update.upgrade_strategy import semantic_versioning


def newer_mapping(image_tags):
    key = list(image_tags.keys())[0]
    tags = {t.strip('v').replace('_', '.'): t for t in image_tags[key]}
    version = semantic_versioning(tags)
    if not version:
        return {}

    return {
        'tags': {key: tags[version]},
        'app_version': tags[version],
    }


if __name__ == '__main__':
    try:
        versions_json = json.loads(sys.stdin.read())
    except ValueError:
        raise ValueError('Invalid json specified')

    print(json.dumps(newer_mapping(versions_json)))
