annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.5.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: IRC Highway eBook Downloads.
home: https://truecharts.org/charts/stable/openbooks
icon: https://truecharts.org/img/hotlink-ok/chart-icons/openbooks.webp
keywords:
  - openbooks
  - media
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: openbooks
sources:
  - https://github.com/evan-buss/openbooks
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/openbooks
  - https://hub.docker.com/r/evanbuss/openbooks
type: application
version: 8.10.1

