annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: games
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.9.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Minecraft Java Dedicated Server
home: https://truecharts.org/charts/stable/minecraft-java
icon: https://truecharts.org/img/hotlink-ok/chart-icons/minecraft-java.webp
keywords:
  - minecraft-java
  - minecraft
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: minecraft-java
sources:
  - https://ghcr.io/itzg/minecraft-server
  - https://github.com/itzg/docker-minecraft-server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/minecraft-java
type: application
version: 35.64.1

