annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.9.41
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Open source server for archival of comics/manga.
home: https://truecharts.org/charts/stable/lanraragi
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lanraragi.webp
keywords:
  - lanraragi
  - comics
  - manga
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: lanraragi
sources:
  - https://github.com/Difegue/LANraragi
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/lanraragi
  - https://hub.docker.com/r/difegue/lanraragi
  - https://sugoi.gitbook.io/lanraragi/
type: application
version: 13.10.1

