annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: AI
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Open-source ChatGPT experience for LLMs, embedders, and vector databases.
home: https://truecharts.org/charts/stable/anything-llm
icon: https://truecharts.org/img/hotlink-ok/chart-icons/anything-llm.webp
keywords:
  - anything-llm
  - ai
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: anything-llm
sources:
  - https://ghcr.io/mintplex-labs/anything-llm
  - https://github.com/Mintplex-Labs/anything-llm
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/anything-llm
type: application
version: 5.10.1

