annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: email
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.7.2
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: Protect your email from spam using disposable addresses.
home: https://truecharts.org/charts/stable/anonaddy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/anonaddy.webp
keywords:
  - anonaddy
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: anonaddy
sources:
  - https://github.com/anonaddy/docker
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/anonaddy
  - https://hub.docker.com/r/anonaddy/anonaddy
type: application
version: 28.25.2

