annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: games
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.10.8
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A private Among Us server
home: https://truecharts.org/charts/stable/impostor-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/impostor-server.webp
keywords:
  - impostor-server
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: impostor-server
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/impostor-server
  - https://hub.docker.com/r/aeonlucid/impostor
type: application
version: 12.10.1

