annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.14.1
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Bridges events and allows you to control your Zigbee devices via MQTT
home: https://truecharts.org/charts/stable/zigbee2mqtt
icon: https://truecharts.org/img/hotlink-ok/chart-icons/zigbee2mqtt.webp
keywords:
  - zigbee
  - mqtt
  - home-assistant
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: zigbee2mqtt
sources:
  - https://github.com/Koenkk/zigbee2mqtt
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/zigbee2mqtt
  - https://hub.docker.com/r/koenkk/zigbee2mqtt
type: application
version: 16.14.1

