annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: networking
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.14.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Out of the box stateless VPN server docker image which starts in just a few seconds and doesn't require persistent storage.
home: https://truecharts.org/charts/stable/dockovpn
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dockovpn.webp
keywords:
  - vpn
  - openvpn
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: dockovpn
sources:
  - https://github.com/dockovpn/dockovpn
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/dockovpn
  - https://hub.docker.com/r/alekslitvinenk/openvpn
type: application
version: 5.10.0

