annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Tools-Utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.0.11
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A stupid simple asset tracker for keeping track of your physical assets, their components, and applicable warranties and routine maintenance.
home: https://truecharts.org/charts/stable/dumbassets
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dumbassets.webp
keywords:
  - dumbassets
  - dumbwareio
  - asset-tracker
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: dumbassets
sources:
  - https://github.com/DumbWareio/dumbassets
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/dumbassets
  - https://hub.docker.com/r/dumbwareio/dumbassets
type: application
version: 3.10.1

