annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 6.3.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Omada is a SDN tool for TP-Link Omada hardware
home: https://truecharts.org/charts/stable/omada-controller
icon: https://truecharts.org/img/hotlink-ok/chart-icons/omada-controller.webp
keywords:
  - omada-controller
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: omada-controller
sources:
  - https://github.com/mbentley/docker-omada-controller
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/omada-controller
  - https://hub.docker.com/r/mbentley/omada-controller
type: application
version: 19.12.0

