annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: database
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.17.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Fast, reliable, scalable, and easy to use open-source relational database system.
home: https://truecharts.org/charts/stable/mariadb
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mariadb.webp
keywords:
  - mariadb
  - mysql
  - database
  - sql
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: mariadb
sources:
  - https://github.com/bitnami/bitnami-docker-mariadb
  - https://github.com/prometheus/mysqld_exporter
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/mariadb
  - https://hub.docker.com/r/bitnamisecure/mariadb
  - https://mariadb.org
type: application
version: 18.9.1

