annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.63.2
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Navidrome is an open source web-based music collection server and streamer
home: https://truecharts.org/charts/stable/navidrome
icon: https://truecharts.org/img/hotlink-ok/chart-icons/navidrome.webp
keywords:
  - navidrome
  - music
  - streaming
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: navidrome
sources:
  - https://github.com/deluan/navidrome
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/navidrome
  - https://hub.docker.com/r/deluan/navidrome
type: application
version: 23.13.1

