# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/deluan/navidrome
  pullPolicy: IfNotPresent
  tag: 0.64.0@sha256:a384948b81bd1529986c5960169e7fc4fa00f46bde6bd517971a4c36671db2af
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ND_MUSICFOLDER: /music
            ND_SCANNER_SCHEDULE: "@every 15m"
            ND_LOGLEVEL: info
            ND_SESSIONTIMEOUT: 24h
            ND_ENABLETRANSCODINGCONFIG: false
service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533
persistence:
  data:
    enabled: true
    mountPath: /data
  music:
    enabled: true
    mountPath: /music
