annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2025.0.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Dokuwiki is a simple to use and highly versatile Open Source wiki software that doesn't require a database.
home: https://truecharts.org/charts/stable/dokuwiki
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dokuwiki.webp
keywords:
  - dokuwiki
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: dokuwiki
sources:
  - https://ghcr.io/dokuwiki/dokuwiki
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/dokuwiki
type: application
version: 16.10.1

