annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Social
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.9.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.9.2
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: Open source decentralized social media platform that's free forever!
home: https://truecharts.org/charts/stable/misskey
icon: https://truecharts.org/img/hotlink-ok/chart-icons/misskey.webp
keywords:
  - Misskey
  - Social
  - Friend
  - Social Media
  - Fediverse
  - ActivityPub
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: misskey
sources:
  - https://github.com/misskey-dev/misskey/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/misskey
  - https://hub.docker.com/r/misskey/misskey
type: application
version: 17.22.0

