annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Other
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: |
  App for taking notes and tracking tasks on a daily basis.
home: https://truecharts.org/charts/stable/dailynotes
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dailynotes.webp
keywords:
  - dailynotes
  - Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: dailynotes
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/dailynotes
  - https://hub.docker.com/r/m0ngr31/dailynotes
type: application
version: 9.10.0

