annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: deemix is a deezer downloader built from the ashes of Deezloader Remix.
home: https://truecharts.org/charts/stable/deemix
icon: https://truecharts.org/img/hotlink-ok/chart-icons/deemix.webp
keywords:
  - music
  - deemix
  - deezer
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: deemix
sources:
  - https://git.freezerapp.xyz/RemixDev/deemix-py
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/deemix
  - https://gitlab.com/Bockiii/deemix-docker.git
type: application
version: 14.10.0

