annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: KitchenOwl is a smart self-hosted grocery list and recipe manager.
home: https://truecharts.org/charts/stable/kitchenowl
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kitchenowl.webp
keywords:
  - recipes
  - kitchen
  - grocery
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: kitchenowl
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/kitchenowl
  - https://hub.docker.com/r/tombursch/kitchenowl
  - https://hub.docker.com/r/tombursch/kitchenowl-web
  - https://tombursch.github.io/kitchenowl
type: application
version: 13.10.1

