annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Cloud
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.10.6
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: YOURLS is a set of PHP scripts that will allow you to run Your Own URL Shortener.
home: https://truecharts.org/charts/stable/yourls
icon: https://truecharts.org/img/hotlink-ok/chart-icons/yourls.webp
keywords:
  - yourls
  - Cloud
  - Tools-Utilities
  - Network-Web
  - Network-Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: yourls
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/yourls
  - https://hub.docker.com/_/yourls
type: application
version: 12.20.1

