annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.4.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Autoscan replaces the default Plex and Emby behaviour for picking up file changes on the file system.
home: https://truecharts.org/charts/stable/autoscan
icon: https://truecharts.org/img/hotlink-ok/chart-icons/autoscan.webp
keywords:
  - autoscan
  - media
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: autoscan
sources:
  - https://github.com/trueforge-org/containers/tree/main/apps/autoscan
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/autoscan
  - https://hotio.dev/containers/autoscan
type: application
version: 12.10.0

