annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.10.1
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A self-hosted BitTorrent indexer, DHT crawler, content classifier and torrent search engine with web UI, GraphQL API and Servarr stack integration.
home: https://truecharts.org/charts/stable/bitmagnet
icon: https://truecharts.org/img/hotlink-ok/chart-icons/bitmagnet.webp
keywords:
  - torrent
  - bitmagnet
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: bitmagnet
sources:
  - https://bitmagnet.io
  - https://ghcr.io/bitmagnet-io/bitmagnet
  - https://github.com/bitmagnet-io/bitmagnet
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/bitmagnet
type: application
version: 5.10.0

