{
 "title": "bitmagnet",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bitmagnet_process_resident_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT crawler torrents persisted per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(bitmagnet_dht_crawler_persisted_total[$__rate_interval])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warnings & Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"bitmagnet\"} | json | severity = \"WARNING\" or severity = \"ERROR\""
    }
   ]
  },
  {
   "title": "DHT query success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(bitmagnet_dht_server_query_success_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT query errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(bitmagnet_dht_server_query_error_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT query latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, bitmagnet_dht_server_query_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT query concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "bitmagnet_dht_server_query_concurrency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Meta info request success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(bitmagnet_meta_info_requester_success_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Meta info request errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "rate(bitmagnet_meta_info_requester_error_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Meta info request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, bitmagnet_meta_info_requester_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Meta info request concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "bitmagnet_meta_info_requester_concurrency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classifier success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(bitmagnet_classifier_success_total[$__rate_interval])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classifier latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, bitmagnet_classifier_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT incoming query success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(bitmagnet_dht_responder_query_success_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT incoming query errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "rate(bitmagnet_dht_responder_query_error_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}