annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Tools-Utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.8.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: GUI for Redis.
home: https://truecharts.org/charts/stable/redisinsight
icon: https://truecharts.org/img/hotlink-ok/chart-icons/redisinsight.webp
keywords:
  - redisinsight
  - Tools-Utilities
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: redisinsight
sources:
  - https://github.com/RedisInsight/RedisInsight
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/redisinsight
  - https://hub.docker.com/r/redislabs/redisinsight
  - https://redis.com/redis-enterprise/redis-insight/
type: application
version: 12.13.1

