annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: radicale
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.8.0.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Radicale is a small but powerful CalDAV (calendars, to-do lists) and CardDAV (contacts) server.
home: https://truecharts.org/charts/stable/radicale
icon: https://truecharts.org/img/hotlink-ok/chart-icons/radicale.webp
keywords:
  - radicale
  - CalDAV
  - CardDAV
  - calendars
  - contacts
  - tasks
  - to-do
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: radicale
sources:
  - https://github.com/Kozea/Radicale
  - https://github.com/tomsquest/docker-radicale
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/radicale
  - https://hub.docker.com/r/tomsquest/docker-radicale
  - https://radicale.org/
type: application
version: 9.12.0

