annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.8.2
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Kiwix enables you to have the whole Wikipedia at hand wherever you go!
home: https://truecharts.org/charts/stable/kiwix-serve
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kiwix-serve.webp
keywords:
  - kiwix-serve
  - Productivity
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: kiwix-serve
sources:
  - https://ghcr.io/kiwix/kiwix-serve
  - https://github.com/kiwix/kiwix-tools/blob/master/docker/server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/kiwix-serve
  - https://www.kiwix.org/
type: application
version: 12.10.1

