# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/kiwix/kiwix-serve
  tag: 3.8.2@sha256:e478554a9920412eeb5ce1d73f24e4b28445ebed233187cdd03c623c32be46a5
service:
  main:
    ports:
      main:
        port: 10323
        protocol: http
persistence:
  data:
    enabled: true
    mountPath: /data

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DOWNLOAD: http://download.kiwix.org/zim/wikipedia_en_chemistry_nopic.zim
            PORT: "{{ .Values.service.main.ports.main.port }}"
          args:
            - "*.zim"
