annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.39.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Plex downloader that brings content from any server to yours!
home: https://truecharts.org/charts/stable/reaparr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/reaparr.webp
keywords:
  - reaparr
  - Backup
  - Downloaders
  - MediaApp-Video
  - MediaApp-Music
  - MediaApp-Photos
  - MediaApp-Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: reaparr
sources:
  - https://github.com/reaparr/reaparr/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/reaparr
  - https://hub.docker.com/r/reaparr/reaparr
type: application
version: 2.13.1

