annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: browser
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1154.0.1
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: a free and open-source web browser developed by the Mozilla Foundation and its subsidiary, the Mozilla Corporation.
home: https://truecharts.org/charts/stable/firefox
icon: https://truecharts.org/img/hotlink-ok/chart-icons/firefox.webp
keywords:
  - firefox
  - browser
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: firefox
sources:
  - https://ghcr.io/linuxserver/firefox
  - https://github.com/linuxserver/docker-firefox
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/firefox
type: application
version: 42.3.0

