# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/firefox
  pullPolicy: IfNotPresent
  tag: 1155.0.1@sha256:bc5b08fa66d505e5a600d474365e57e2d858bcf12d4e80e7c79a3d3dc3b7ca66
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10131
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            FM_HOME: "/config"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
            TITLE: "TrueChartVNC Client"
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: false
