# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/librespeed
  tag: 6.3.0@sha256:5e7ba354832be35ed2638f58ff035e101c6494d7282a2cf88aa180545d7fd58c
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10016
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
