annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 18.7.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: XWiki is a free wiki software platform written in Java with a design emphasis on extensibility
home: https://truecharts.org/charts/stable/xwiki
icon: https://truecharts.org/img/hotlink-ok/chart-icons/xwiki.webp
keywords:
  - xwiki
  - wiki
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: xwiki
sources:
  - https://gallery.ecr.aws/docker/library/xwiki
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/xwiki
  - https://github.com/xwiki/xwiki-docker
type: application
version: 18.16.1

