# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/photostructure/server
  tag: 2026.9.1-beta@sha256:77dde8a99c52927a5e1dcbeac0ee54f8e2230d57411ee1b6ed0cbff5ab652919
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        protocol: http
        port: 1787

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PS_HTTP_PORT: "{{ .Values.service.main.ports.main.port }}"
            PS_LOG_LEVEL: "error"

persistence:
  config:
    enabled: true
    mountPath: /ps/config
  library:
    enabled: true
    mountPath: /ps/library
  logs:
    enabled: true
    mountPath: /ps/logs
  tempscratchdisk:
    enabled: true
    mountPath: /ps/tmp
