annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.36.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Audiobookshelf is a self-hosted audiobook server for managing and playing your audiobooks.
home: https://truecharts.org/charts/stable/audiobookshelf
icon: https://truecharts.org/img/hotlink-ok/chart-icons/audiobookshelf.webp
keywords:
  - audiobookshelf
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: audiobookshelf
sources:
  - https://github.com/advplyr/audiobookshelf
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/audiobookshelf
  - https://hub.docker.com/r/advplyr/audiobookshelf
type: application
version: 13.13.1

