annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: monitor
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.20.1
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A discord bot that monitors your game server and tracks the live data of your game servers.
home: https://truecharts.org/charts/stable/discordgsm
icon: https://truecharts.org/img/hotlink-ok/chart-icons/discordgsm.webp
keywords:
  - discordgsm
  - game-server
  - monitor
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: discordgsm
sources:
  - https://github.com/DiscordGSM/GameServerMonitor
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/discordgsm
  - https://hub.docker.com/r/discordgsm/discord-game-server-monitor
type: application
version: 11.10.1

