annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: hosting
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 9.6.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Mattermost is an open source platform for secure collaboration across the entire software development lifecycle.
home: https://truecharts.org/charts/stable/mattermost
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mattermost.webp
keywords:
  - team
  - mattermost
  - development
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: mattermost
sources:
  - https://github.com/mattermost/docker
  - https://github.com/mattermost/mattermost-server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/mattermost
  - https://hub.docker.com/r/mattermost/mattermost-enterprise-edition
type: application
version: 16.10.1

