annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: MediaApp-Other
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.9.7
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: This is the unified client for Notifiarr.com. The client enables content requests from Media Bot in your Discord Server and also provides reports for Plex usage and system health among many other features.
home: https://truecharts.org/charts/stable/notifiarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/notifiarr.webp
keywords:
  - plex
  - discord
  - MediaApp-Other
  - notification
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: notifiarr
sources:
  - https://github.com/Notifiarr/notifiarr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/notifiarr
  - https://hub.docker.com/r/golift/notifiarr
type: application
version: 8.10.1

