annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Networking
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 10.6.101
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Ubiquiti Network's Unifi Controller
home: https://truecharts.org/charts/stable/unifi
icon: https://truecharts.org/img/hotlink-ok/chart-icons/unifi.webp
keywords:
  - ubiquiti
  - unifi
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: unifi
sources:
  - https://ghcr.io/goofball222/unifi
  - https://github.com/jacobalberty/unifi-docker
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/unifi
  - https://unifi-network.ui.com
type: application
version: 26.15.1

