annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Network-FTP
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.7.5
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: 'Fully featured and highly configurable SFTP server with optional HTTP/S, FTP, FTPS and WebDAV support. Several storage backends are supported: local filesystem, encrypted local filesystem, S3 (compatible) Object Storage, Google Cloud Storage, Azure Blob Storage, SFTP.'
home: https://truecharts.org/charts/stable/sftpgo
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sftpgo.webp
keywords:
  - sftpgo
  - Network-FTP
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: sftpgo
sources:
  - https://ghcr.io/drakkan/sftpgo
  - https://github.com/drakkan/sftpgo
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/sftpgo
type: application
version: 10.10.0

