annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Other
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: No description provide.
home: https://truecharts.org/charts/stable/fsm
icon: https://truecharts.org/img/hotlink-ok/chart-icons/fsm.webp
keywords:
  - fsm
  - Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: fsm
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/fsm
  - https://hub.docker.com/r/ofsm/ofsm
  - https://registry.hub.docker.com/r/ofsm/ofsm
type: application
version: 9.10.1

