annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.11.0
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Netdata is high-fidelity infrastructure monitoring and troubleshooting.
home: https://truecharts.org/charts/stable/netdata
icon: https://truecharts.org/img/hotlink-ok/chart-icons/netdata.webp
keywords:
  - netdata
  - monitoring
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: netdata
sources:
  - https://ghcr.io/netdata/netdata
  - https://github.com/netdata
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/netdata
type: application
version: 14.12.1

