annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Backup
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.0.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A high-performance, enterprise-grade system for backing up Linux, Windows and macOS PCs and laptops to a server's disk.
home: https://truecharts.org/charts/stable/backuppc
icon: https://truecharts.org/img/hotlink-ok/chart-icons/backuppc.webp
keywords:
  - backuppc
  - Backup
  - Network-Web
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: backuppc
sources:
  - https://backuppc.github.io/backuppc/index.html
  - https://ghcr.io/adferrand/backuppc
  - https://github.com/adferrand/docker-backuppc
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/backuppc
type: application
version: 11.7.1

