annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Kapowarr is a software to build and manage a comic book library, fitting in the *arr suite of software.
home: https://truecharts.org/charts/stable/kapowarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kapowarr.webp
keywords:
  - kapowarr
  - comic
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: kapowarr
sources:
  - https://github.com/Casvt/Kapowarr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/kapowarr
  - https://hub.docker.com/r/mrcas/kapowarr
type: application
version: 4.10.1

