annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.60.4
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: The best and simplest free open source website change detection, website watcher, restock monitor and notification service
home: https://truecharts.org/charts/stable/changedetection-io
icon: https://truecharts.org/img/hotlink-ok/chart-icons/changedetection-io.webp
keywords:
  - monitoring
  - changedection
  - website watcher
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: changedetection-io
sources:
  - https://changedetection.io/
  - https://ghcr.io/dgtlmoon/changedetection.io
  - https://github.com/dgtlmoon/changedetection.io/tree/master
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/changedetection-io
type: application
version: 6.12.2

