annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.61.1
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Browserless is a web-service that allows for remote clients to connect, drive, and execute headless work
home: https://truecharts.org/charts/stable/browserless-chrome
icon: https://truecharts.org/img/hotlink-ok/chart-icons/browserless-chrome.webp
keywords:
  - browserless
  - chrome
  - puppeteer
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: browserless-chrome
sources:
  - https://docs.browserless.io/docs/docker.html
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/browserless-chrome
  - https://hub.docker.com/r/browserless/chrome
type: application
version: 13.10.1

