annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Tools-Utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Not everyone, especially people new to Linux and Unraid, know what a command that they type i will actually do.
home: https://truecharts.org/charts/stable/explainshell
icon: https://truecharts.org/img/hotlink-ok/chart-icons/explainshell.webp
keywords:
  - explainshell
  - Tools-Utilities
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: explainshell
sources:
  - https://github.com/idank/explainshell
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/explainshell
  - https://hub.docker.com/r/spaceinvaderone/explainshell
type: application
version: 9.10.1

