annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: network
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.9.1
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Client for Cloudflare Tunnel, a daemon that exposes private services through the Cloudflare edge.
home: https://truecharts.org/charts/stable/cloudflared
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cloudflared.webp
keywords:
  - cloudflared
  - networking
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: cloudflared
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/cloudflared
  - https://hub.docker.com/r/cloudflare/cloudflared
type: application
version: 16.15.1

