# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: 2026.9.0@sha256:ff69a2225ad7c6f85ed84fbd5f3087df46202426b2388ec60214098e0adf05e9
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            TUNNEL_TOKEN: ""
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
