annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: GIT
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.27.3
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: memcached
    version: 17.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: memcached.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Self hosted GIT repositories
home: https://truecharts.org/charts/stable/gitea
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gitea.webp
keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - gitea
  - gogs
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: gitea
sources:
  - https://gitea.com/gitea/helm-chart
  - https://github.com/go-gitea/gitea
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/gitea
  - https://hub.docker.com/r/gitea/gitea
type: application
version: 24.22.1

