annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.39.1
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Dillinger is a cloud-enabled, mobile-ready, offline-storage, AngularJS powered HTML5 Markdown editor.
home: https://truecharts.org/charts/stable/dillinger
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dillinger.webp
keywords:
  - dillinger
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: dillinger
sources:
  - https://ghcr.io/linuxserver/dillinger
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/dillinger
type: application
version: 13.10.0

