annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Generate a full web-page screenshot with our service, that provides rich interface to make any kind of web screenshots online for free with no limits. The simplest way to take a full page screenshot.
home: https://truecharts.org/charts/stable/website-shot
icon: https://truecharts.org/img/hotlink-ok/chart-icons/website-shot.webp
keywords:
  - website-shot
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: website-shot
sources:
  - https://github.com/Flowko/website-shot
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/website-shot
  - https://hub.docker.com/r/flowko1/website-shot
type: application
version: 14.10.1

