annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 26.08.2
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: MKVToolNix is a set of tools to create, alter and inspect Matroska files.
home: https://truecharts.org/charts/stable/mkvtoolnix
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mkvtoolnix.webp
keywords:
  - media
  - mkvtoolnix
  - mkv
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: mkvtoolnix
sources:
  - https://github.com/jlesage/docker-mkvtoolnix
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/mkvtoolnix
  - https://hub.docker.com/r/jlesage/mkvtoolnix
  - https://mkvtoolnix.download/
type: application
version: 16.13.0

