annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: file-sharing
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.11.2
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Local file sharing in your web browser.
home: https://truecharts.org/charts/stable/pairdrop
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pairdrop.webp
keywords:
  - file-sharing
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pairdrop
sources:
  - https://ghcr.io/schlagmichdoch/pairdrop
  - https://github.com/schlagmichdoch/PairDrop
  - https://github.com/schlagmichdoch/PairDrop/pkgs/container/pairdrop
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/pairdrop
type: application
version: 3.10.0

