annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 26.05.20260608
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A simple, self-hosted, easy-to-use platform for organising and storing information.
home: https://truecharts.org/charts/stable/bookstack
icon: https://truecharts.org/img/hotlink-ok/chart-icons/bookstack.webp
keywords:
  - bookstack
  - book
  - stack
  - organizer
  - server
  - hosted
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: bookstack
sources:
  - https://ghcr.io/linuxserver/bookstack
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/bookstack
  - https://www.bookstackapp.com/
type: application
version: 21.21.1

