# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: oci.trueforge.org/containerforge/duplicacy
  tag: 1.8.0@sha256:5c6940ac1e0748ec817860d4ead305c543096738a90628d556dd8b2de4e1c238
securityContext:
  container:
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 3875
        protocol: http
        targetPort: 3875
persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs
