annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: iot
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A free and non-commercial open-source operating system alternative for running a cloud-free smart-home IoT.
home: https://truecharts.org/charts/stable/raspberrymatic
icon: https://truecharts.org/img/hotlink-ok/chart-icons/raspberrymatic.webp
keywords:
  - raspberrymatic
  - iot
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: raspberrymatic
sources:
  - https://ghcr.io/jens-maus/raspberrymatic
  - https://github.com/jens-maus/RaspberryMatic
  - https://github.com/jens-maus/RaspberryMatic/pkgs/container/raspberrymatic
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/raspberrymatic
type: application
version: 9.10.0

