annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Cloud
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 7.4.7
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Jupyter a web based IDE
home: https://truecharts.org/charts/stable/jupyter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jupyter.webp
keywords:
  - Jupyter
  - Notebook
  - Lab
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: jupyter
sources:
  - https://github.com/jupyter/docker-stacks
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/jupyter
  - https://quay.io/jupyter/all-spark-notebook
  - https://quay.io/jupyter/base-notebook
  - https://quay.io/jupyter/datascience-notebook
  - https://quay.io/jupyter/minimal-notebook
  - https://quay.io/jupyter/pyspark-notebook
  - https://quay.io/jupyter/r-notebook
  - https://quay.io/jupyter/scipy-notebook
  - https://quay.io/jupyter/tensorflow-notebook
type: application
version: 13.10.0

