image:
  repository: quay.io/jupyter/base-notebook
  pullPolicy: IfNotPresent
  tag: 2025-03-21@sha256:796f155dd7b1ef06d1f81458eb4e7e891b57a84f3ce98bae73261ac3db5e8066
minimalImage:
  repository: quay.io/jupyter/minimal-notebook
  pullPolicy: IfNotPresent
  tag: 2025-03-21@sha256:ca3267257885c2887398c1ff852c0211f5b3eec1018acb441ee737fb2a15d70f
rImage:
  repository: quay.io/jupyter/r-notebook
  pullPolicy: IfNotPresent
  tag: 2025-03-21@sha256:34867555df2da8b371935304093dcd34a5633509d41bd49f61266c80cef38b05
scipyImage:
  repository: quay.io/jupyter/scipy-notebook
  pullPolicy: IfNotPresent
  tag: 2025-03-21@sha256:df4d4607d258c89d6179d76df8deddb9eaab97510711855d360cccffc3a0b2ae
tensorflowImage:
  repository: quay.io/jupyter/tensorflow-notebook
  pullPolicy: IfNotPresent
  tag: 2025-03-21@sha256:bb141b72eb93459ae03d16ca030b51628ee7c11c67304ca6ebbfc1bdc0780209
datascienceImage:
  repository: quay.io/jupyter/datascience-notebook
  pullPolicy: IfNotPresent
  tag: 2025-03-21@sha256:9f92807a83f934a78328d08b82859ed8052ee32449ce448644ec94e518dbedcd
pysparkImage:
  repository: quay.io/jupyter/pyspark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-03-21@sha256:b592262b3bb7caae49b29d5b0d1e2bce125012cfe976d8a00af4809d4b4f735a
allsparkImage:
  repository: quay.io/jupyter/all-spark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-03-21@sha256:182480ceb30251899236d64919bf4358237fde1af68a27f3cb602dbdd98fbe2b
jupyter:
  jupyter_cmd: lab
  restartable: true
service:
  main:
    ports:
      main:
        port: 10300
        protocol: http
        targetPort: 8888
persistence:
  data:
    enabled: true
    mountPath: /home/jovyan/work
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            NB_UID: "{{ .Values.securityContext.container.PUID }}"
            NB_GID: "{{ .Values.securityContext.pod.fsGroup }}"
            NB_UMASK: "{{ .Values.securityContext.container.UMASK }}"
            # User Defined
            DOCKER_STACKS_JUPYTER_CMD: "{{ .Values.jupyter.jupyter_cmd }}"
            RESTARTABLE: '{{ ternary "yes" "no" .Values.jupyter.restartable }}'
updated: true
