image:
  repository: quay.io/jupyter/base-notebook
  pullPolicy: IfNotPresent
  tag: 2025-07-21@sha256:8fa87589362183594d8113eca6856789e6b4cd3ed4d9631b8fbded1e2c07bdc2
minimalImage:
  repository: quay.io/jupyter/minimal-notebook
  pullPolicy: IfNotPresent
  tag: 2025-07-21@sha256:ea1adac6ee075cdadcbba6020ed5e67198814dae04d26d5d8e87417caf9f3a3d
rImage:
  repository: quay.io/jupyter/r-notebook
  pullPolicy: IfNotPresent
  tag: 2025-07-21@sha256:1d1b8104db0d372fe5a069f9441919de28a481d7660dffb1522fa8ac704a025b
scipyImage:
  repository: quay.io/jupyter/scipy-notebook
  pullPolicy: IfNotPresent
  tag: 2025-07-21@sha256:d7569d1c4182b85d4b2a08e382185891366debe6ef9ce840274adf6c030fcadf
tensorflowImage:
  repository: quay.io/jupyter/tensorflow-notebook
  pullPolicy: IfNotPresent
  tag: 2025-07-21@sha256:afce66f08cf9cd0c85385e904485464f2e140fc1b726268cb44d3bc71aafd5d0
datascienceImage:
  repository: quay.io/jupyter/datascience-notebook
  pullPolicy: IfNotPresent
  tag: 2025-07-21@sha256:c8a31a629cd58bc9d418df8057b41fa7f4e630edfbcb16f5adb2b0ed99271576
pysparkImage:
  repository: quay.io/jupyter/pyspark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-07-21@sha256:ee14815aeab2f317066f77ffad35e07f02cf20d760ec1c931005462de25f5f07
allsparkImage:
  repository: quay.io/jupyter/all-spark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-07-21@sha256:ce1206118af3e311d7770ae0a50f1d70445937c66867b7eacdac3d8a44ca6922
jupyter:
  jupyter_cmd: lab
  restartable: true
service:
  main:
    ports:
      main:
        port: 10300
        protocol: http
        targetPort: 8888
persistence:
  data:
    enabled: true
    mountPath: /home/jovyan/work

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            NB_UID: "{{ .Values.securityContext.container.PUID }}"
            NB_GID: "{{ .Values.securityContext.pod.fsGroup }}"
            NB_UMASK: "{{ .Values.securityContext.container.UMASK }}"
            # User Defined
            DOCKER_STACKS_JUPYTER_CMD: "{{ .Values.jupyter.jupyter_cmd }}"
            RESTARTABLE: '{{ ternary "yes" "no" .Values.jupyter.restartable }}'
updated: true
