annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: networking
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.07.2
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: DNS and Ad-filtering for your network
home: https://truecharts.org/charts/stable/pihole
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pihole.webp
keywords:
  - DNS
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pihole
sources:
  - https://ghcr.io/pi-hole/pihole
  - https://github.com/pi-hole
  - https://github.com/pi-hole/docker-pi-hole
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/pihole
  - https://pi-hole.net/
type: application
version: 22.14.1

