annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Tools-Utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: SUI Startpage is a simple and clean server start page or homepage that you can quickly and easily setup to access your server resources and quick booksmarks and also lets you search on various provider sites via a search bar at the top as well.
home: https://truecharts.org/charts/stable/suistartpage
icon: https://truecharts.org/img/hotlink-ok/chart-icons/suistartpage.webp
keywords:
  - suistartpage
  - Tools-Utilities
  - Network-Web
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: suistartpage
sources:
  - https://github.com/CorneliousJD/SUI-Startpage
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/suistartpage
  - https://hub.docker.com/r/corneliousjd/sui-startpage
type: application
version: 9.10.1

