annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.0.0
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Docker registry v2 command line client and repo listing generator with security checks.
home: https://truecharts.org/charts/stable/reg
icon: https://truecharts.org/img/hotlink-ok/chart-icons/reg.webp
keywords:
  - reg
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: reg
sources:
  - https://github.com/genuinetools/reg
  - https://github.com/k8s-at-home/container-images/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/reg
  - https://hub.docker.com/_/registry
type: application
version: 18.10.0

