annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: GameServers
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.10.8
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Crafty Controller is a Minecraft Server Control Panel / Launcher.
home: https://truecharts.org/charts/stable/crafty-4
icon: https://truecharts.org/img/hotlink-ok/chart-icons/crafty-4.webp
keywords:
  - crafty-4
  - GameServers
  - Other
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: crafty-4
sources:
  - https://craftycontrol.com/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/crafty-4
  - https://gitlab.com/crafty-controller/crafty-4
type: application
version: 11.10.0

