#!/usr/bin/env bash
set -eu

echo "Welcome to the TrueCharts HotPatcher for TrueNAS SCALE RC2"
echo "This tool is going to patch your system to fix performance of the Apps interface..."
echo ""
echo "---"
echo "Applying HotPatch 1"
( wget -q -P /tmp https://github.com/truecharts/apps/raw/master/tools/RC2-HP1.deb && echo "download completed" || echo "download failed" ) && ( dpkg -i /tmp/RC2-HP1.deb 2> /dev/null && echo "patch completed" || echo "patch failed" ) && rm -rf /tmp/RC2-HP1.deb
echo ""
echo "---"
echo "Applying HotPatch 2"
( wget -q -P /tmp https://github.com/truecharts/apps/raw/master/tools/RC2-HP2.patch && echo "download completed" || echo "download failed" ) && ( patch -N -s -p0 -d /usr/lib/python3/dist-packages/middlewared/ < /tmp/RC2-HP2.patch && echo "patch completed" || echo "patch failed" ) && rm -rf /tmp/RC2-HP2.patch

echo "Restarting Middleware..." && systemctl restart middlewared
