# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/calibre
  tag: 9.14.0@sha256:9c153bd9915c9748863e8c452426e99e23ec0a961ca351195acb3b1662b59e7b
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8084
        protocol: tcp
        targetPort: 8080
  webserver:
    enabled: true
    ports:
      webserver:
        enabled: true
        port: 8081
        protocol: http
        targetPort: 8081
ingress:
  webserver:
    enabled: false
    targetSelector:
      webserver: webserver
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CLI_ARGS:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
