annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 9.1.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Professional Photo Management with the Power of Open Source
home: https://truecharts.org/charts/stable/digikam
icon: https://truecharts.org/img/hotlink-ok/chart-icons/digikam.webp
keywords:
  - digikam
  - photo
  - management
  - image
  - gallery
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: digikam
sources:
  - https://ghcr.io/linuxserver/digikam
  - https://github.com/linuxserver/docker-digikam
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/digikam
  - https://www.digikam.org/
type: application
version: 17.11.0

