# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/digikam
  pullPolicy: IfNotPresent
  tag: 9.1.0@sha256:46df01fae3647fc1393af4773b2c600c2884e638b29736fa3740a26136c7072a
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10033
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
