annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: office
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 9.4.0
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: valkey
    version: 2.10.0
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: redis
    tags: []
    import-values: []
deprecated: false
description: 'ONLYOFFICE Document Server is an online office suite comprising viewers and editors for texts, spreadsheets and presentations, fully compatible with Office Open XML formats: .docx, .xlsx, .pptx and enabling collaborative editing in real time.'
home: https://truecharts.org/charts/stable/onlyoffice-document-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/onlyoffice-document-server.webp
keywords:
  - onlyoffice
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: onlyoffice-document-server
sources:
  - https://github.com/ONLYOFFICE/Docker-DocumentServer
  - https://github.com/ONLYOFFICE/DocumentServer
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/onlyoffice-document-server
  - https://hub.docker.com/r/onlyoffice/documentserver
type: application
version: 25.20.1

