{{/* Define the configmap */}}
{{- define "docspell.configmap" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docspell-env
data:
  {{/* RESTSERVER */}}
  DOCSPELL_SERVER_BACKEND_JDBC_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  {{/* General */}}
  DOCSPELL_SERVER_APP__ID: "restserver-{{ randAlphaNum 10 }}"
  DOCSPELL_SERVER_APP__NAME: "{{ .Values.rest.app.name }}"
  DOCSPELL_SERVER_BACKEND_FILES_CHUNK__SIZE: "{{ .Values.rest.app.chunk_size }}"
  DOCSPELL_SERVER_INTERNAL__URL: "http://{{ include "common.names.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.main.ports.main.port }}"
  DOCSPELL_SERVER_BASE__URL: "{{ .Values.rest.app.base_url }}"
  DOCSPELL_SERVER_MAX__ITEM__PAGE__SIZE: "{{ .Values.rest.app.max_page_size }}"
  DOCSPELL_SERVER_MAX__NOTE__LENGTH: "{{ .Values.rest.app.max_char_length }}"
  DOCSPELL_SERVER_SHOW__CLASSIFICATION__SETTINGS: "{{ .Values.rest.app.classification_enabled }}"
  DOCSPELL_SERVER_BIND_ADDRESS: "{{ .Values.rest.app.bind_address }}"
  DOCSPELL_SERVER_BIND_PORT: "{{ .Values.service.main.ports.main.port }}"
  {{/* Mail */}}
  DOCSPELL_SERVER_BACKEND_MAIL__DEBUG: "{{ .Values.rest.mail.debug_enabled }}"
  {{/* SOLR */}}
  DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED: "{{ .Values.rest.solr.enabled }}"
  DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_COMMIT__WITHIN: "{{ .Values.rest.solr.commit_within }}"
  DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_DEF__TYPE: "{{ .Values.rest.solr.parser }}"
  DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_LOG__VERBOSE: "{{ .Values.rest.solr.debug_enabled }}"
  DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_Q__OP: "{{ .Values.rest.solr.combiner }}"
  DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL: "http://{{ include "common.names.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.solr.ports.solr.port }}/solr/docspell"
  {{/* Auth */}}
  DOCSPELL_SERVER_AUTH_REMEMBER__ME_ENABLED: "{{ .Values.rest.auth.remember_me_enabled }}"
  DOCSPELL_SERVER_AUTH_REMEMBER__ME_VALID: "{{ .Values.rest.auth.remember_me_valid }}"
  DOCSPELL_SERVER_AUTH_SESSION__VALID: "{{ .Values.rest.auth.session_valid }}"
  DOCSPELL_SERVER_AUTH_SERVER__SECRET: "{{ .Values.rest.auth.server_secret }}"
  DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET: "{{ .Values.rest.auth.admin_endpoint_secret }}"
  {{/* Singup */}}
  DOCSPELL_SERVER_BACKEND_SIGNUP_MODE: "{{ .Values.rest.singup.mode }}"
  DOCSPELL_SERVER_BACKEND_SIGNUP_INVITE__TIME: "{{ .Values.rest.singup.invite_time }}"
  DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD: "{{ .Values.rest.singup.invite_password }}"
  {{/* Integration */}}
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED: "{{ .Values.rest.integration.enabled }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_PRIORITY: "{{ .Values.rest.integration.priority }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_SOURCE__NAME: "{{ .Values.rest.integration.source_name }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ALLOWED__IPS_ENABLED: "{{ .Values.rest.integration.allowed_ips_enabled }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__BASIC_ENABLED: "{{ .Values.rest.integration.http_basic_enabled }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED: "{{ .Values.rest.integration.http_header_enabled }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__NAME: "{{ .Values.rest.integration.http_header_name }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE: "{{ .Values.rest.integration.http_header_value }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__BASIC_USER: "{{ .Values.rest.integration.http_basic_user }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__BASIC_PASSWORD: "{{ .Values.rest.integration.http_basic_password }}"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__BASIC_REALM: "{{ .Values.rest.integration.http_basic_realm }}"
  {{/* JOEX */}}
  DOCSPELL_JOEX_JDBC_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  {{/* General */}}
  DOCSPELL_JOEX_APP__ID: "joex-{{ randAlphaNum 10 }}"
  DOCSPELL_JOEX_FILES_CHUNK__SIZE: "{{ .Values.joex.app.chunk_size }}"
  DOCSPELL_JOEX_BASE__URL: "{{ .Values.joex.app.base_url }}"
  DOCSPELL_JOEX_BIND_ADDRESS: "{{ .Values.joex.app.bind_address }}"
  DOCSPELL_JOEX_BIND_PORT: "{{ .Values.service.joex.ports.joex.port }}"
  {{/* Mail */}}
  DOCSPELL_JOEX_MAIL__DEBUG: "{{ .Values.joex.mail.debug_enabled }}"
  DOCSPELL_JOEX_SEND__MAIL_LIST__ID: "{{ .Values.joex.mail.send_mail_list_id }}"
  {{/* SOLR */}}
  DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED: "{{ .Values.joex.solr.enabled }}"
  DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL: "http://{{ include "common.names.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.solr.ports.solr.port }}/solr/docspell"
  DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_COMMIT__WITHIN: "{{ .Values.joex.solr.commit_within }}"
  DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_DEF__TYPE: "{{ .Values.joex.solr.parser }}"
  DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_Q__OP: "{{ .Values.joex.solr.combiner }}"
  DOCSPELL_JOEX_FULL__TEXT__SEARCH_MIGRATION_INDEX__ALL__CHUNK: "{{ .Values.joex.solr.index_chunk }}"
  DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_LOG__VERBOSE: "{{ .Values.joex.solr.logs_verbose }}"
  {{/* Convert */}}
  DOCSPELL_JOEX_CONVERT_CHUNK__SIZE: "{{ .Values.joex.convert.chunk_size }}"
  DOCSPELL_JOEX_CONVERT_CONVERTED__FILENAME__PART: "{{ .Values.joex.convert.converted_filename_part }}"
  DOCSPELL_JOEX_CONVERT_DECRYPT__PDF_ENABLED: "{{ .Values.joex.convert.decrypt_pdf_enabled }}"
  DOCSPELL_JOEX_CONVERT_MARKDOWN_INTERNAL__CSS: "{{ .Values.joex.convert.md_internal_css }}"
  DOCSPELL_JOEX_CONVERT_MAX__IMAGE__SIZE: "{{ .Values.joex.convert.max_image_size }}"
  DOCSPELL_JOEX_CONVERT_OCRMYPDF_ENABLED: "{{ .Values.joex.convert.ocrmypdf_enabled }}"
  DOCSPELL_JOEX_CONVERT_OCRMYPDF_COMMAND_PROGRAM: "{{ .Values.joex.convert.ocrmypdf_cmd_program }}"
  DOCSPELL_JOEX_CONVERT_OCRMYPDF_COMMAND_TIMEOUT: "{{ .Values.joex.convert.ocrmypdf_cmd_timeout }}"
  DOCSPELL_JOEX_CONVERT_OCRMYPDF_WORKING__DIR: "{{ .Values.joex.convert.ocrmypdf_workdir }}"
  DOCSPELL_JOEX_CONVERT_TESSERACT_COMMAND_PROGRAM: "{{ .Values.joex.convert.tesseract_cmd_program }}"
  DOCSPELL_JOEX_CONVERT_TESSERACT_COMMAND_TIMEOUT: "{{ .Values.joex.convert.tesseract_cmd_timeout }}"
  DOCSPELL_JOEX_CONVERT_TESSERACT_WORKING__DIR: "{{ .Values.joex.convert.tesseract_workdir }}"
  DOCSPELL_JOEX_CONVERT_UNOCONV_COMMAND_PROGRAM: "{{ .Values.joex.convert.unoconv_cmd_program}}"
  DOCSPELL_JOEX_CONVERT_UNOCONV_COMMAND_TIMEOUT: "{{ .Values.joex.convert.unoconv_cmd_timeout }}"
  DOCSPELL_JOEX_CONVERT_UNOCONV_WORKING__DIR: "{{ .Values.joex.convert.unoconv_workdir }}"
  DOCSPELL_JOEX_CONVERT_WKHTMLPDF_COMMAND_PROGRAM: "{{ .Values.joex.convert.wkhtmlpdf_cmd_program }}"
  DOCSPELL_JOEX_CONVERT_WKHTMLPDF_COMMAND_TIMEOUT: "{{ .Values.joex.convert.wkhtmlpdf_cmd_timeout }}"
  DOCSPELL_JOEX_CONVERT_WKHTMLPDF_WORKING__DIR: "{{ .Values.joex.convert.whhtmlpdf_workdir }}"
  {{/* Extraction */}}
  DOCSPELL_JOEX_EXTRACTION_OCR_GHOSTSCRIPT_COMMAND_PROGRAM: "{{ .Values.joex.extraction.gs_cmd }}"
  DOCSPELL_JOEX_EXTRACTION_OCR_GHOSTSCRIPT_COMMAND_TIMEOUT: "{{ .Values.joex.extraction.gs_cmd_timeout }}"
  DOCSPELL_JOEX_EXTRACTION_OCR_GHOSTSCRIPT_WORKING__DIR: "{{ .Values.joex.extraction.gs_workdir }}"
  DOCSPELL_JOEX_EXTRACTION_OCR_MAX__IMAGE__SIZE: "{{ .Values.joex.extraction.max_image_size }}"
  DOCSPELL_JOEX_EXTRACTION_OCR_PAGE__RANGE_BEGIN: "{{ .Values.joex.extraction.page_range_begin }}"
  DOCSPELL_JOEX_EXTRACTION_OCR_TESSERACT_COMMAND_PROGRAM: "{{ .Values.joex.extraction.tesseract_cmd_program }}"
  DOCSPELL_JOEX_EXTRACTION_OCR_TESSERACT_COMMAND_TIMEOUT: "{{ .Values.joex.extraction.tesseract_cmd_timeout }}"
  DOCSPELL_JOEX_EXTRACTION_OCR_UNPAPER_COMMAND_PROGRAM: "{{ .Values.joex.extraction.unpaper_cmd_program }}"
  DOCSPELL_JOEX_EXTRACTION_OCR_UNPAPER_COMMAND_TIMEOUT: "{{ .Values.joex.extraction.unpaper_cmd_timeout }}"
  DOCSPELL_JOEX_EXTRACTION_PDF_MIN__TEXT__LEN: "{{ .Values.joex.extraction.pdf_min_text_length }}"
  DOCSPELL_JOEX_EXTRACTION_PREVIEW_DPI: "{{ .Values.joex.extraction.preview_dpi }}"
  {{/* House Keeping */}}
  DOCSPELL_JOEX_HOUSE__KEEPING_CHECK__NODES_ENABLED: "{{ .Values.joex.housekeeping.check_nodes_enabled }}"
  DOCSPELL_JOEX_HOUSE__KEEPING_CHECK__NODES_MIN__NOT__FOUND: "{{ .Values.joex.housekeeping.check_nodes_min_not_found }}"
  DOCSPELL_JOEX_HOUSE__KEEPING_CLEANUP__INVITES_ENABLED: "{{ .Values.joex.housekeeping.cleanup_invites_enabled }}"
  DOCSPELL_JOEX_HOUSE__KEEPING_CLEANUP__INVITES_OLDER__THAN: "{{ .Values.joex.housekeeping.cleanup_invites_older_than }}"
  DOCSPELL_JOEX_HOUSE__KEEPING_CLEANUP__JOBS_ENABLED: "{{ .Values.joex.housekeeping.cleanup_jobs_enabled }}"
  DOCSPELL_JOEX_HOUSE__KEEPING_CLEANUP__JOBS_DELETE__BATCH: "{{ .Values.joex.housekeeping.cleanup_jobs_delete_batch }}"
  DOCSPELL_JOEX_HOUSE__KEEPING_CLEANUP__JOBS_OLDER__THAN: "{{ .Values.joex.housekeeping.cleanup_jobs_older_than }}"
  DOCSPELL_JOEX_HOUSE__KEEPING_CLEANUP__REMEMBER__ME_ENABLED: "{{ .Values.joex.housekeeping.cleanup_remember_me_enabled }}"
  DOCSPELL_JOEX_HOUSE__KEEPING_CLEANUP__REMEMBER__ME_OLDER__THAN: "{{ .Values.joex.housekeeping.cleanup_remember_me_older_than }}"
  DOCSPELL_JOEX_HOUSE__KEEPING_SCHEDULE: "{{ .Values.joex.housekeeping.schedule }}"
  {{/* Scheduler */}}
  DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME: "{{ .Values.joex.scheduler.periodic_name }}"
  DOCSPELL_JOEX_PERIODIC__SCHEDULER_WAKEUP__PERIOD: "{{ .Values.joex.scheduler.periodic_wakeup_period }}"
  DOCSPELL_JOEX_SCHEDULER_COUNTING__SCHEME: "{{ .Values.joex.scheduler.counting_scheme }}"
  DOCSPELL_JOEX_SCHEDULER_LOG__BUFFER__SIZE: "{{ .Values.joex.scheduler.log_buffer_size }}"
  DOCSPELL_JOEX_SCHEDULER_NAME: "{{ .Values.joex.scheduler.name }}"
  DOCSPELL_JOEX_SCHEDULER_POOL__SIZE: "{{ .Values.joex.scheduler.pool_size }}"
  DOCSPELL_JOEX_SCHEDULER_RETRIES: "{{ .Values.joex.scheduler.retries }}"
  DOCSPELL_JOEX_SCHEDULER_RETRY__DELAY: "{{ .Values.joex.scheduler.retry_delay }}"
  DOCSPELL_JOEX_SCHEDULER_WAKEUP__PERIOD: "{{ .Values.joex.scheduler.wakeup_period }}"
  {{/* Text Analysis */}}
  DOCSPELL_JOEX_TEXT__ANALYSIS_CLASSIFICATION_ENABLED: "{{ .Values.joex.textanalysis.classification_enabled }}"
  DOCSPELL_JOEX_TEXT__ANALYSIS_CLASSIFICATION_ITEM__COUNT: "{{ .Values.joex.textanalysis.classification_item_count }}"
  DOCSPELL_JOEX_TEXT__ANALYSIS_MAX__LENGTH: "{{ .Values.joex.textanalysis.max_length }}"
  DOCSPELL_JOEX_TEXT__ANALYSIS_NLP_CLEAR__INTERVAL: "{{ .Values.joex.textanalysis.nlp_clear_interval }}"
  DOCSPELL_JOEX_TEXT__ANALYSIS_NLP_MAX__DUE__DATE__YEARS: "{{ .Values.joex.textanalysis.nlp_max_due_date_years }}"
  DOCSPELL_JOEX_TEXT__ANALYSIS_NLP_MODE: "{{ .Values.joex.textanalysis.nlp_mode }}"
  DOCSPELL_JOEX_TEXT__ANALYSIS_NLP_REGEX__NER_FILE__CACHE__TIME: "{{ .Values.joex.textanalysis.nlp_regex_ner_file_cache_time }}"
  DOCSPELL_JOEX_TEXT__ANALYSIS_NLP_REGEX__NER_MAX__ENTRIES: "{{ .Values.joex.textanalysis.nlp_regex_ner_max_entries }}"
  DOCSPELL_JOEX_TEXT__ANALYSIS_WORKING__DIR: "{{ .Values.joex.textanalysis.workdir }}"
  {{/* Update Check */}}
  DOCSPELL_JOEX_UPDATE__CHECK_ENABLED: "{{ .Values.joex.updatecheck.enabled }}"
  DOCSPELL_JOEX_UPDATE__CHECK_BODY: "{{ .Values.joex.updatecheck.body }}"
  DOCSPELL_JOEX_UPDATE__CHECK_SCHEDULE: "{{ .Values.joex.updatecheck.schedule }}"
  DOCSPELL_JOEX_UPDATE__CHECK_SENDER__ACCOUNT: "{{ .Values.joex.updatecheck.sender_account }}"
  DOCSPELL_JOEX_UPDATE__CHECK_SMTP__ID: "{{ .Values.joex.updatecheck.smtp_id }}"
  DOCSPELL_JOEX_UPDATE__CHECK_SUBJECT: "{{ .Values.joex.updatecheck.subject }}"
  DOCSPELL_JOEX_UPDATE__CHECK_TEST__RUN: "{{ .Values.joex.updatecheck.test_run }}"
  {{/* User Tasks */}}
  DOCSPELL_JOEX_USER__TASKS_SCAN__MAILBOX_MAIL__CHUNK__SIZE: "{{ .Values.joex.usertasks.scan_mailbox_chunk_size }}"
  DOCSPELL_JOEX_USER__TASKS_SCAN__MAILBOX_MAX__FOLDERS: "{{ .Values.joex.usertasks.scan_mailbox_max_folders }}"
  DOCSPELL_JOEX_USER__TASKS_SCAN__MAILBOX_MAX__MAILS: "{{ .Values.joex.usertasks.scan_mailbox_max_mails }}"
{{- end -}}
