annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Tools-Utilities
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 8.7.2
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A command-line application that will automatically synchronize recommended settings from TRaSH guides to your Sonarr/Radarr instances.
home: https://truecharts.org/charts/stable/recyclarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/recyclarr.webp
keywords:
  - recyclarr
  - Tools-Utilities
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: recyclarr
sources:
  - https://ghcr.io/recyclarr/recyclarr
  - https://github.com/recyclarr/recyclarr
  - https://github.com/recyclarr/recyclarr/pkgs/container/recyclarr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/recyclarr
type: application
version: 15.12.0

