annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.2.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: An open-source single page application to view your photos in the easiest way possible.
home: https://truecharts.org/charts/stable/pixapop
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pixapop.webp
keywords:
  - pixapop
  - photo
  - gallery
  - image
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: pixapop
sources:
  - https://ghcr.io/linuxserver/pixapop
  - https://github.com/bierdok/pixapop
  - https://github.com/linuxserver/docker-pixapop
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/pixapop
type: application
version: 14.10.1

