annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: network
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.13.0
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: |
  Deploys a CSI-Addons controller implementation for Kubernetes. CSI-Addons may
  be bundled with the Kubernetes distribution, this chart is meant for cases
  where it is not.
home: https://truecharts.org/charts/stable/csi-addons-controller
icon: https://truecharts.org/img/hotlink-ok/chart-icons/csi-addons-controller.webp
keywords:
  - storage
  - snapshot
  - validation
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: csi-addons-controller
sources:
  - https://github.com/csi-addons/kubernetes-csi-addons
  - https://github.com/kubernetes-csi/external-snapshotter/
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/csi-addons-controller
  - https://quay.io/csiaddons/k8s-controller
type: application
version: 2.10.1

