annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: networking
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: DNS Chart service for a steam cache.
home: https://truecharts.org/charts/stable/lancache-dns
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lancache-dns.webp
keywords:
  - lancache-dns
  - dns
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: lancache-dns
sources:
  - https://github.com/lancachenet/lancache-dns
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/lancache-dns
  - https://hub.docker.com/r/lancachenet/lancache-dns
type: application
version: 12.10.0

