annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.0.16
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Expose all events from an Amcrest device to an MQTT broker
home: https://truecharts.org/charts/stable/amcrest2mqtt
icon: https://truecharts.org/img/hotlink-ok/chart-icons/amcrest2mqtt.webp
keywords:
  - amcrest2mqtt
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: amcrest2mqtt
sources:
  - https://github.com/dchesterton/amcrest2mqtt
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/amcrest2mqtt
  - https://hub.docker.com/r/dchesterton/amcrest2mqtt
type: application
version: 15.10.0

