annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.6.0
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Guacd - Apache Guacamole is a clientless remote desktop gateway.
home: https://truecharts.org/charts/stable/guacd
icon: https://truecharts.org/img/hotlink-ok/chart-icons/guacd.webp
keywords:
  - guacd
  - guacamole
  - remote
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: guacd
sources:
  - https://github.com/apache/guacamole-server
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/guacd
  - https://hub.docker.com/r/guacamole/guacd
type: application
version: 13.10.1

