annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: Downloaders
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: RadarrSync Syncs two Radarr servers through web API. This is a modified version designed to be run in a Chart Chart. This version supports only two servers.
home: https://truecharts.org/charts/stable/radarrsync
icon: https://truecharts.org/img/hotlink-ok/chart-icons/radarrsync.webp
keywords:
  - radarrsync
  - Downloaders
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: radarrsync
sources:
  - https://github.com/dairefinn/RadarrSync
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/radarrsync
  - https://hub.docker.com/r/dmanius/radarrsync-docker
type: application
version: 9.10.1

