annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.14.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Quassel-core is a modern, cross-platform, distributed IRC client.
home: https://truecharts.org/charts/stable/quassel-core
icon: https://truecharts.org/img/hotlink-ok/chart-icons/quassel-core.webp
keywords:
  - quassel-core
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: quassel-core
sources:
  - https://ghcr.io/linuxserver/quassel-core
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/quassel-core
type: application
version: 15.10.0

