annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: monitor
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.1.25
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A simple discord/telegram/slack bot to monitor your game servers and players in style.
home: https://truecharts.org/charts/stable/game-server-watcher
icon: https://truecharts.org/img/hotlink-ok/chart-icons/game-server-watcher.webp
keywords:
  - game-server-watcher
  - monitoring
  - bots
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: game-server-watcher
sources:
  - https://ghcr.io/a-sync/game-server-watcher
  - https://github.com/a-sync/game-server-watcher
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/game-server-watcher
type: application
version: 5.10.1

