annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: music
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.8.1
dependencies:
  - name: common
    version: 29.20.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: SheetAble is an easy to use music sheet organiser for all the music enthusiasts out there.
home: https://truecharts.org/charts/stable/sheetable
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sheetable.webp
keywords:
  - sheetable
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: sheetable
sources:
  - https://github.com/SheetAble
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/sheetable
  - https://hub.docker.com/r/vallezw/sheetable
  - https://sheetable.net/docs
type: application
version: 10.10.1

