annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2026.9.2
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A lightweight NodeJS server that emulates the iOS HomeKit API
home: https://truecharts.org/charts/stable/homebridge
icon: https://truecharts.org/img/hotlink-ok/chart-icons/homebridge.webp
keywords:
  - homebridge
  - homekit
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: homebridge
sources:
  - https://ghcr.io/homebridge/homebridge
  - https://github.com/oznu/docker-homebridge
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/homebridge
  - https://homebridge.io/
type: application
version: 13.5.0

