annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: incubator
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.3.20230704
dependencies:
  - name: common
    version: 29.20.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Nntp2nntp proxy allow you to use your NNTP Account from multiple systems, each with own user name and password.
home: https://truecharts.org/charts/stable/nntp2nntp
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nntp2nntp.webp
keywords:
  - nntp2nntp
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: nntp2nntp
sources:
  - https://ghcr.io/linuxserver/nntp2nntp
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/nntp2nntp
type: application
version: 13.10.1

