annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 3.4.1
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: seerr is a fork of Overseerr with support for Jellyfin and Emby. It can be used to manage requests for your media library.
home: https://truecharts.org/charts/stable/seerr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/seerr.webp
keywords:
  - seerr
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: seerr
sources:
  - https://github.com/seerr-team/seerr
  - https://github.com/trueforge-org/containers/tree/main/apps/seerr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/seerr
type: application
version: 16.7.0

