annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 4.4.20260907
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Healthchecks is a cron job monitoring service. It listens for HTTP requests and email messages ("pings") from your cron jobs and scheduled tasks ("checks"). When a ping does not arrive on time, Healthchecks sends out alerts.
home: https://truecharts.org/charts/stable/healthchecks
icon: https://truecharts.org/img/hotlink-ok/chart-icons/healthchecks.webp
keywords:
  - cron
  - monitoring
  - alert
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: healthchecks
sources:
  - https://ghcr.io/linuxserver/healthchecks
  - https://github.com/healthchecks/healthchecks
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/healthchecks
type: application
version: 19.14.0

