image:
  repository: ghcr.io/linuxserver/healthchecks
  tag: 3.10.20250721@sha256:3864b8a601eda7fbedd785714712540ceceb03e8c582b82e8891e23f3d7f6ff6
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10074
        targetPort: 8000
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            REGENERATE_SETTINGS: "True"
            SITE_ROOT: "https://healthchecks.domain"
            SITE_NAME: ""
            SUPERUSER_EMAIL: "email@healthchecks.io"
            SUPERUSER_PASSWORD: "myVeryStrongPassword"
