# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/healthchecks
  tag: 4.4.20260907@sha256:e762ed89d9316148a6bbc3feff5b7a53096e41c0bb4c4f672477931256a6faf9
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10074
        targetPort: 8000
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            REGENERATE_SETTINGS: "True"
            SITE_ROOT: "https://healthchecks.domain"
            SITE_NAME: ""
            SUPERUSER_EMAIL: "email@healthchecks.io"
            SUPERUSER_PASSWORD: "myVeryStrongPassword"
