annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2024.3.1
dependencies:
  - name: common
    version: 29.20.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: An Automatic Video Library Manager for TV Shows
home: https://truecharts.org/charts/stable/sickchill
icon: https://truecharts.org/img/hotlink-ok/chart-icons/sickchill.webp
keywords:
  - sickchill
  - video
  - library
  - manager
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: sickchill
sources:
  - https://ghcr.io/linuxserver/sickchill
  - https://github.com/SickChill/SickChill
  - https://github.com/linuxserver/docker-sickchill
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/sickchill
type: application
version: 15.10.1

