annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 2.6.3.5592
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Indexer manager/proxy built on the popular arr net base stack to integrate with your various PVR apps.
home: https://truecharts.org/charts/stable/prowlarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/prowlarr.webp
keywords:
  - prowlarr
  - torrent
  - usenet
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: prowlarr
sources:
  - https://ghcr.io/onedr0p/exportarr
  - https://github.com/Prowlarr/Prowlarr
  - https://github.com/k8s-at-home/container-images
  - https://github.com/trueforge-org/containers/tree/main/apps/prowlarr
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/prowlarr
type: application
version: 22.13.0

