{
 "title": "Prowlarr",
 "tags": [
  "prowlarr",
  "music",
  "movies",
  "tv",
  "media"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "prowlarr_instance",
    "label": "Prowlarr Instance",
    "query": {
     "query": "label_values({__name__=~\"prowlarr_.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_system_status{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"prowlarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Health Issues"
    },
    {
     "expr": "max(prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Enabled Indexers"
    },
    {
     "expr": "max(prowlarr_indexer_total{instance=~\"${prowlarr_instance}\"} - prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Disabled Indexers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Grabs"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Query Failures"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Response Time"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) / sum(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Failed Queries"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(prowlarr_indexer_vip_expires_in_seconds)",
     "legendFormat": "Nearest VIP Expiration"
    }
   ]
  },
  {
   "title": "Indexer Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"}) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Agent Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"}[$__rate_interval])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VIP Expiration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "prowlarr_indexer_vip_expires_in_seconds{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() * 1000) + (prowlarr_indexer_vip_expires_in_seconds{instance=~\"${prowlarr_instance}\"} * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}