annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.13.1
dependencies:
  - name: common
    version: 29.19.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A self-hosted image sharing platform built with Symfony and SvelteKit️.
home: https://truecharts.org/charts/stable/slink
icon: https://truecharts.org/img/hotlink-ok/chart-icons/slink.webp
keywords:
  - media
  - photos
  - pictures
  - sharing
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: slink
sources:
  - https://github.com/andrii-kryvoviaz/slink
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/slink
  - https://hub.docker.com/r/anirdev/slink
type: application
version: 6.14.0

