image:
  repository: docker.io/anirdev/slink
  pullPolicy: IfNotPresent
  tag: v1.4.3@sha256:c4aab6fe11eba2fda297807cda6ff8ae220de2ffc8c725daaa57a386a91e7e7a
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ORIGIN: "{{ .Values.chartContext.appUrl }}"
            USER_APPROVAL_REQUIRED: true
            IMAGE_MAX_SIZE: "15M"
persistence:
  database:
    enabled: true
    mountPath: "/app/var/data"
  images:
    enabled: true
    mountPath: "/app/slink/images"
portal:
  open:
    enabled: true
ingress:
  main:
    required: true
