annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: AI
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.5.9
dependencies:
  - name: common
    version: 29.20.1
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: the AI-native open-source embedding database.
home: https://truecharts.org/charts/stable/chroma
icon: https://truecharts.org/img/hotlink-ok/chart-icons/chroma.webp
keywords:
  - chroma
  - embedding
  - database
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: chroma
sources:
  - https://ghcr.io/chroma-core/chroma
  - https://github.com/chroma-core/chroma
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/chroma
type: application
version: 7.10.1

