annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: gaming
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    version: 29.20.0
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Hytale blends sandbox freedom with RPG adventure in a procedurally generated world full of dungeons, creatures, and secrets you shape block by block.
home: https://truecharts.org/charts/stable/hytale
icon: https://truecharts.org/img/hotlink-ok/chart-icons/hytale.webp
keywords:
  - hytale
  - gaming
  - multiplayer
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: hytale
sources:
  - https://github.com/trueforge-org/containers/tree/main/apps/hytale
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/hytale
  - https://hytale.com
type: application
version: 2.10.1

